import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {bootstrapExtension,currentExtensionWorker,registeredExtension} from '../src/extension-bootstrap.mjs';
import path from 'node:path';
const expected='chrome-extension://'+ 'a'.repeat(32)+'/background.js';
test('already-loaded extension is attested without issuing a second load command',async()=>{const wanted={id:'a',version:'0.8.1',path:path.resolve('synthetic-extension')};let reads=0;const result=await registeredExtension(async()=>({extensions:++reads===1?[{...wanted,enabled:false}]:[{...wanted,enabled:true}]}),wanted,{timeoutMs:50,pollMs:2});assert.equal(result.id,'a');assert.equal(reads,2);await assert.rejects(registeredExtension(async()=>({extensions:[{...wanted,enabled:true,path:path.resolve('wrong-extension')}]}),wanted,{timeoutMs:5,pollMs:1}),/EXTENSION_LOAD_UNCONFIRMED/);});
function fixture(){const worker=new EventEmitter();worker.url=()=>expected;let members=[worker],calls=0;worker.evaluate=async()=>{calls++;return true;};return {worker,context:{serviceWorkers:()=>members},expected,config:{synthetic:true},contextTimeoutMs:15,activationTimeoutMs:15,writeTimeoutMs:15,calls:()=>calls,replace:()=>members=[{url:()=>expected}]};}
test('installation events do not select a stale or ambiguous worker generation',async()=>{const old={url:()=>expected},fresh={url:()=>expected};let members=[old,fresh];setTimeout(()=>members=[fresh],5);assert.equal(await currentExtensionWorker({serviceWorkers:()=>members},expected,{settleMs:2,timeoutMs:60}),fresh);await assert.rejects(currentExtensionWorker({serviceWorkers:()=>[old,fresh]},expected,{settleMs:2,timeoutMs:10}),/EXTENSION_WORKER_UNCONFIRMED/);});
test('capability delivery follows generation, context and activation confirmation',async()=>{const f=fixture(),phases=[];await bootstrapExtension({...f,note:(p,s)=>phases.push([p,s])});assert.equal(f.calls(),3);assert.deepEqual(phases,[['extension_context',undefined],['extension_context','ok'],['extension_activation',undefined],['extension_activation','ok'],['extension_bootstrap',undefined],['extension_bootstrap','ok']]);assert.equal(f.worker.listenerCount('close'),0);});
test('replaced or missing context refuses capability delivery',async()=>{const f=fixture();f.worker.evaluate=async()=>{f.replace();return true;};await assert.rejects(bootstrapExtension(f),/EXTENSION_WORKER_REPLACED/);const g=fixture();g.worker.evaluate=async()=>false;await assert.rejects(bootstrapExtension(g),/EXTENSION_CONTEXT_UNAVAILABLE/);});
test('old generations may retire during activation but never coexist during capability delivery',async()=>{const f=fixture(),old={url:()=>expected.replace('background.js','old.js')};let members=[old,f.worker],calls=0;f.context.serviceWorkers=()=>members;f.worker.evaluate=async(_fn,arg)=>{calls++;if(calls===2)members=[f.worker];if(calls===3){assert.equal(members.length,1);assert.equal(arg,f.config);}return true;};await bootstrapExtension({...f,confirm:async sole=>{if(sole)assert.equal(members.length,1);}});assert.equal(calls,3);});
test('context timeout, storage timeout and worker closure are separately bounded',async()=>{
 const a=fixture();a.worker.evaluate=()=>new Promise(()=>{});await assert.rejects(bootstrapExtension(a),/EXTENSION_CONTEXT_TIMEOUT/);
 const b=fixture();let n=0;b.worker.evaluate=()=>++n<=2?Promise.resolve(true):new Promise(()=>{});await assert.rejects(bootstrapExtension(b),/BROWSER_BOOTSTRAP_TIMEOUT/);
 const c=fixture();c.worker.evaluate=()=>{queueMicrotask(()=>c.worker.emit('close'));return new Promise(()=>{});};await assert.rejects(bootstrapExtension(c),/EXTENSION_WORKER_REPLACED/);
});
