import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {freshSandbox} from '../scripts/test-sandbox.mjs';
import {prepareExtension} from '../src/prepare-extension.mjs';
async function fixture(config='placeholder',dependency='export const value=1;'){const box=await freshSandbox('wp16-entry');await fs.writeFile(path.join(box.root,'manifest.json'),JSON.stringify({version:'0.8.1',background:{service_worker:'background.js'}}));await fs.writeFile(path.join(box.root,'background.js'),"import './dependency.js';");await fs.writeFile(path.join(box.root,'dependency.js'),dependency);await fs.writeFile(path.join(box.root,'config.js'),config);return box;}
test('entry fingerprint is deterministic and excludes dynamic config contents',async()=>{const a=await fixture('SYNTHETIC_DYNAMIC_A'),b=await fixture('SYNTHETIC_DYNAMIC_B');try{const x=await prepareExtension(a.root),y=await prepareExtension(b.root);assert.equal(x.background.service_worker,y.background.service_worker);assert.match(x.background.service_worker,/^background\.[a-f0-9]{24}\.js$/);assert.equal((await fs.readFile(path.join(a.root,'config.js'),'utf8')).includes('SYNTHETIC_DYNAMIC'),false);}finally{await a.cleanup();await b.cleanup();}});
test('an imported static module change also changes the background entry URL',async()=>{const a=await fixture(),b=await fixture('placeholder','export const value=2;');try{assert.notEqual((await prepareExtension(a.root)).background.service_worker,(await prepareExtension(b.root)).background.service_worker);}finally{await a.cleanup();await b.cleanup();}});
test('hard-linked config is refused before any write reaches an outside file',async()=>{const box=await fixture(),outside=await freshSandbox('wp16-outside'),file=path.join(outside.root,'keep');await fs.writeFile(file,'keep');await fs.unlink(path.join(box.root,'config.js'));await fs.link(file,path.join(box.root,'config.js'));try{await assert.rejects(prepareExtension(box.root),/UNSAFE_EXTENSION/);assert.equal(await fs.readFile(file,'utf8'),'keep');}finally{await fs.unlink(path.join(box.root,'config.js'));await box.cleanup();await outside.cleanup();}});
