// Fixed self-owned test endpoints only; never returns SDP/credentials/payload.
export function canaryExpression(udpPort){return `(()=>{
globalThis.__transportProbe={rtcStarted:false,rtcOfferSet:false,rtcState:'new',rtcError:null,webTransportStarted:false,webTransportError:null,socketOpened:false,socketEchoed:false,socketError:null};
fetch('http://127.0.0.1:49190/direct').catch(()=>{});const image=new Image();image.src='http://127.0.0.1:49190/image';document.body.append(image);
for(const url of ['ws://127.0.0.1:49190/socket','wss://127.0.0.1:49190/socket']){try{const s=new WebSocket(url);s.onerror=()=>{};}catch{}}
const frame=document.createElement('iframe');frame.src='http://127.0.0.1:49189/frame-probe';document.body.append(frame);
try{const p=new RTCPeerConnection({iceServers:[{urls:'stun:127.0.0.1:${udpPort}'},{urls:'turn:127.0.0.1:49190?transport=tcp',username:'synthetic',credential:'synthetic-not-a-secret'}]});globalThis.__transportPc=p;globalThis.__transportProbe.rtcStarted=true;p.onicegatheringstatechange=()=>globalThis.__transportProbe.rtcState=p.iceGatheringState;p.createDataChannel('synthetic-counter');p.createOffer().then(o=>p.setLocalDescription(o)).then(()=>globalThis.__transportProbe.rtcOfferSet=true).catch(e=>globalThis.__transportProbe.rtcError=e.name);}catch(e){globalThis.__transportProbe.rtcError=e.name;}
try{const w=new WebTransport('https://127.0.0.1:${udpPort}/');globalThis.__transportProbe.webTransportStarted=true;w.ready.catch(e=>globalThis.__transportProbe.webTransportError=e.name);}catch(e){globalThis.__transportProbe.webTransportError=e.name;}
return {requested:true};})()`;}
export const publicSocketProbe="(()=>{try{const s=new WebSocket('wss://ws.postman-echo.com/raw');s.onopen=()=>{globalThis.__transportProbe.socketOpened=true;s.send('SYNTHETIC_PUBLIC_PROBE');};s.onmessage=e=>{globalThis.__transportProbe.socketEchoed=e.data==='SYNTHETIC_PUBLIC_PROBE';s.close();};s.onerror=()=>globalThis.__transportProbe.socketError='socket-error';}catch(e){globalThis.__transportProbe.socketError=e.name;}return {requested:true};})()";

export function webTransportProbe(port){return `(()=>{globalThis.__webTransportProbe={requested:true,available:typeof WebTransport==='function',started:false,error:null,cspViolation:false};document.addEventListener('securitypolicyviolation',e=>{try{if(new URL(e.blockedURI).origin==='https://127.0.0.1:${port}')globalThis.__webTransportProbe.cspViolation=true;}catch{}},{once:false});try{const w=new WebTransport('https://127.0.0.1:${port}/');globalThis.__webTransportProbe.started=true;w.ready.catch(e=>globalThis.__webTransportProbe.error=e.name);}catch(e){globalThis.__webTransportProbe.error=e.name;}return {requested:true};})()`;}
