import {randomUUID} from 'node:crypto';import {verifyDeployment,plainPath,POWERSHELL,VERSION,runtimeEnvironment} from './deployment.mjs';import fs from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import {ROOT,STATE,PROFILE,result,fail,bounded,budgets,requestBudget} from './wire.mjs';import {management,invoke,end} from './session.mjs';import {stdoutUntil,outputFailedExit} from './output.mjs';
async function readStdin(){let data=Buffer.alloc(0);try{await bounded((async()=>{for await(const b of process.stdin){if(data.length+b.length>60000)throw fail('INPUT_LIMIT');data=Buffer.concat([data,b]);}})(),performance.now()+5000,'INPUT_DEADLINE');}finally{process.stdin.destroy();}try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(data));}catch{throw fail('INVALID_JSON');}}
export async function start(claimId=randomUUID()){
 if(!/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(claimId))throw fail('INVALID_CLAIM');
 await verifyDeployment();const acl=spawn(POWERSHELL,['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(ROOT,'scripts/prepare-state.ps1'),'-Path',STATE],{windowsHide:true,env:runtimeEnvironment(),stdio:['ignore','ignore','ignore']});const aclExit=await bounded(new Promise((resolve,reject)=>{acl.on('error',()=>reject(fail('ACL_HELPER')));acl.on('close',resolve);}),performance.now()+10000);if(aclExit!==0)throw fail('STATE_ACL');
 try{await fs.stat(path.join(STATE,'service.json'));const existing=await management('status');return {...existing,data:{...existing.data,created:false}};}catch(e){if(e.code!=='ENOENT')throw e;}
 const created=JSON.parse(await fs.readFile(path.join(ROOT,'PROFILE-CREATED.json'),'utf8'));if(created.path!==PROFILE||created.createdEmpty!==true)throw fail('SHARED_PROFILE_RECEIPT');await plainPath(PROFILE,{directory:true});
 const launcher=spawn(path.join(ROOT,'dist/pipe-gate.exe'),['launch',process.execPath,path.join(ROOT,'scripts/server.mjs')],{windowsHide:true,env:{...runtimeEnvironment(),ABW19_START_CLAIM:claimId},stdio:['ignore','pipe','ignore']});let launchText='';launcher.stdout.on('data',b=>{if(launchText.length<4096)launchText+=b.toString('utf8');});
 const launchExit=await bounded(new Promise((resolve,reject)=>{launcher.once('error',()=>reject(fail('SERVICE_LAUNCH_FAILED')));launcher.once('close',resolve);}),performance.now()+5000,'SERVICE_LAUNCH_UNKNOWN');if(launchExit!==0)throw fail('SERVICE_LAUNCH_FAILED');let spawned;try{spawned=JSON.parse(launchText);}catch{throw fail('SERVICE_LAUNCH_PROOF_UNKNOWN');}if(!Number.isInteger(spawned.gatePid)||spawned.gatePid<=0||spawned.launcherPid!==launcher.pid||spawned.handlesInherited!==false||!/^[0-9a-f]{16}$/.test(spawned.gateCreationHex))throw fail('SERVICE_LAUNCH_PROOF_UNKNOWN');
 const deadline=performance.now()+30000;while(performance.now()<deadline){try{const receiptFile=path.join(STATE,'gate-exit-'+spawned.gatePid+'.json');const receipt=JSON.parse(await fs.readFile(receiptFile,'utf8'));const bornMs=Number(BigInt('0x'+spawned.gateCreationHex)/10000n-11644473600000n);if(receipt.gatePid===spawned.gatePid&&(await fs.stat(receiptFile)).birthtimeMs>=bornMs-1)throw fail('SERVICE_START_FAILED');}catch(e){if(e.code==='SERVICE_START_FAILED')throw e;if(e.code!=='ENOENT'&&e instanceof SyntaxError)throw fail('SERVICE_START_UNKNOWN');}try{const ready=await management('status');if(ready.ok&&ready.data.claimId===claimId&&ready.data.gatePid===spawned.gatePid){const proof={created:true,claimId,gatePid:spawned.gatePid,launcherPid:spawned.launcherPid,gateCreationHex:spawned.gateCreationHex,launchMode:'isolated-native',servicePid:ready.data.servicePid,hostPid:ready.data.hostPid};await fs.writeFile(path.join(STATE,'launch-'+claimId+'.json'),JSON.stringify(proof),{flag:'wx'});return {...ready,data:{...ready.data,...proof}};}if(ready.ok)throw fail('START_INSTANCE_NOT_OWNED');}catch(e){if(e.code==='START_INSTANCE_NOT_OWNED'||e.code==='EEXIST')throw e;}await new Promise(r=>setTimeout(r,100));}throw fail('SERVICE_START_UNKNOWN');
}
async function main(){await verifyDeployment();const args=process.argv.slice(2),command=args.shift();const positional=[];const opts={};while(args.length){const a=args.shift();if(a.startsWith('--')){if(!['--task','--input','--output','--agent-name','--display-name','--allow-origin','--claim-id','--expect-instance'].includes(a)||!args.length||(a!=='--allow-origin'&&opts[a]!==undefined))throw fail('INVALID_ARGUMENTS');if(a==='--allow-origin'){(opts[a]??=[]).push(args.shift());if(opts[a].length>8)throw fail('INVALID_ORIGINS');}else opts[a]=args.shift();}else positional.push(a);}
 if(command==='version')return result(true,{version:VERSION,scope:'same-machine candidate',tools:11}); if(command==='experience'){throw fail('UNSUPPORTED');const launched=await start(opts['--claim-id']);if(opts['--claim-id']&&(!launched.data?.created||launched.data.claimId!==opts['--claim-id']))throw fail('START_INSTANCE_NOT_OWNED');return launched;}if(command==='start')return start(opts['--claim-id']);if(command==='status')return management('status',{},opts['--expect-instance']);if(command==='stop')return management('stop',{},opts['--expect-instance']);
 if(command==='task')return management('task',{alias:positional[0],agent:opts['--agent-name']||'Agent',display:opts['--display-name']||positional[0],origins:opts['--allow-origin']},opts['--expect-instance']);
 if(command==='end')return end(positional[0],opts['--expect-instance']);if(command==='call'){if(opts['--input']!==undefined&&opts['--input']!=='-')throw fail('INPUT_STDIN_ONLY');const input=opts['--input']==='-'?await readStdin():{};return invoke(opts['--task'],positional[0],input,opts['--output']!==undefined?{output:opts['--output']}:{},opts['--expect-instance']);}
 if(command==='mcp'){const {serve}=await import('./mcp.mjs');await serve(opts['--task'],opts['--expect-instance']);return null;}
 throw fail('UNSUPPORTED');
}
if(path.resolve(process.argv[1]||'')===import.meta.filename){await budgets.run(performance.now()+30000,async()=>{let r;try{r=await main();}catch(e){r=result(false,null,e.code||'COMMAND_FAILED');}if(r){try{await stdoutUntil(JSON.stringify(r)+'\n',requestBudget());process.exitCode=r.ok?0:1;}catch{outputFailedExit();}}});}
