import dgram from 'node:dgram';
import http from 'node:http';
// Only listeners created by this invocation are rolled back. Preserve bind error.
async function bind(server,port){await new Promise((resolve,reject)=>{const error=e=>reject(e);server.once('error',error);server.listen(port,'127.0.0.1',()=>{server.off('error',error);resolve();});});}
async function closeOwned(server){if(!server.listening)return;server.closeAllConnections();let timer;try{await Promise.race([new Promise((resolve,reject)=>server.close(e=>e?reject(e):resolve())),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error('FIXTURE_ROLLBACK_TIMEOUT'),{code:'FIXTURE_ROLLBACK_TIMEOUT'})),2000);})]);}finally{clearTimeout(timer);}}
export async function fixture(){
 let udpReceipts=0,tcpAccepts=0;const udpCanary=dgram.createSocket('udp4');udpCanary.on('message',()=>udpReceipts++);await new Promise((resolve,reject)=>{udpCanary.once('error',reject);udpCanary.bind(0,'127.0.0.1',resolve);});
 let canary=0;const canaryCategories={direct:0,image:0,dedicated:0,shared:0,service:0,frame:0,socket:0,other:0};
 const canaryServer=http.createServer((request,response)=>{canary++;const category=(request.url||'').split('?')[0].slice(1);canaryCategories[Object.hasOwn(canaryCategories,category)?category:'other']++;response.writeHead(200,{'Access-Control-Allow-Origin':'*'});response.end('OWN_CANARY');});
 canaryServer.on('connection',()=>tcpAccepts++);
 canaryServer.on('upgrade',(_request,socket)=>{canary++;canaryCategories.socket++;socket.destroy();});
 let redirect=false,slow=false;
 const server=http.createServer((request,response)=>{
  if(redirect&&request.url==='/agent-b'){response.writeHead(302,{Location:'http://127.0.0.1:1/forbidden','Cache-Control':'no-store'});response.end();return;}
  if(['/worker.js','/shared-worker.js','/service-worker.js'].includes(request.url)){response.writeHead(200,{'Content-Type':'application/javascript','Cache-Control':'no-store'});if(request.url==='/worker.js')response.end("fetch('http://127.0.0.1:49190/dedicated').then(()=>postMessage('reached')).catch(()=>postMessage('blocked'));");else if(request.url==='/shared-worker.js')response.end("onconnect=e=>{const port=e.ports[0];port.onmessage=()=>fetch('http://127.0.0.1:49190/shared').then(()=>port.postMessage('reached')).catch(()=>port.postMessage('blocked'));port.start();};");else response.end("self.addEventListener('install',e=>e.waitUntil(fetch('http://127.0.0.1:49190/service')));");return;}
  if(request.url==='/frame-probe'){canary++;canaryCategories.frame++;response.writeHead(200,{'Content-Type':'text/html'});response.end('<p>OWN_FRAME_CANARY</p>');return;}
  if(request.url==='/style.css'){response.writeHead(200,{'Content-Type':'text/css'});response.end('body{border-top:6px solid #325f4d} #fixture-photo{width:64px;height:64px}');return;}
  if(request.url==='/sample.svg'){response.writeHead(200,{'Content-Type':'image/svg+xml'});response.end('<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><rect width="64" height="64" fill="#325f4d"/><circle cx="32" cy="32" r="18" fill="#bfe0c9"/></svg>');return;}
  const fixturePath=(request.url||'').split('?')[0];const index=fixturePath==='/agent-a'?0:fixturePath==='/agent-b'?1:-1;if(index<0){response.writeHead(404);response.end();return;}
  const letter=index?'B':'A',wash=index?'#eef2f8':'#edf4ef';
  response.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; worker-src 'self'; img-src 'self' http://127.0.0.1:1 http://127.0.0.1:49190; connect-src 'self' http://127.0.0.1:49190 ws://127.0.0.1:49190 wss://127.0.0.1:49190 wss://ws.postman-echo.com https://127.0.0.1:"+udpCanary.address().port+"; frame-src 'self' https:"});
  const send=()=>response.end(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><link rel="stylesheet" href="/style.css"><title>${request.url.includes('long=1')?'很长的中文网页标题用于检查单行省略与任务状态互不重叠：恢复已批准的暗色侧栏聚焦总览，所有八个页面仍然可见。':'演示页面 '+letter}</title><style>:root{--bg:${wash};--ink:#273b30;--line:#cbd8cd;--accent:#325f4d}*{box-sizing:border-box;letter-spacing:0}body{margin:0;color:var(--ink);background:var(--bg);font:17px/1.8 'Microsoft YaHei UI','Segoe UI',sans-serif}header{padding:28px 40px;border-bottom:1px solid var(--line)}main{padding:30px 40px;min-height:1900px}h1{font-size:26px;font-weight:500;margin:8px 0}small{color:#64746a}input,button{font:inherit;padding:8px 14px;border:1px solid var(--line);border-radius:4px;background:white}button{color:var(--accent);cursor:pointer}section{margin:28px 0;padding:24px 0;border-top:1px solid var(--line)}#zone{min-height:540px;background:${wash}}a{color:var(--accent)}</style><header><small>测试 Agent ${letter} · 独立网页 · 共享新 Profile</small><h1>演示页面 ${letter}</h1></header><main><img id="fixture-photo" src="/sample.svg"><section id="zone"><h2 id="marker">${letter}_REV_0</h2><p>确认接管后可以在这份真实 WebView2 网页中输入。</p><label>姓名<input id="name" aria-label="姓名"></label><textarea id="notes" aria-label="备注"></textarea><input id="agree" type="checkbox"><select id="choice"><option value="a">A</option><option value="b">B</option></select><input id="saved" value="${letter}_SEED" aria-label="演示输入框"><button id="bump" onclick="window.__demoRevision=(window.__demoRevision||0)+1;document.querySelector('#marker').textContent='HUMAN_'+window.__demoRevision">增加页面计数</button><p><a href="#kept">添加一项页面历史</a></p><p>该页面仅由本机 loopback 提供，没有真实账号或已有资料。</p></section><section><h2>滚动保持区域</h2><p>在不同 Agent 页面之间切换，再回到本页查看滚动与输入状态。</p></section></main><script>window.__inputEvents=[];for(const name of ['click','input','keydown','keyup','wheel'])document.addEventListener(name,e=>{if(window.__inputEvents.length<300)window.__inputEvents.push({type:e.type,trusted:e.isTrusted,target:e.target.id||'',key:e.key||'',data:e.data||''});},true);</script></html>`);if(slow&&index===0)setTimeout(send,1500);else send();
 });
 try{await bind(canaryServer,49190);await bind(server,49189);}
 catch(error){udpCanary.close();for(const owned of [server,canaryServer])try{await closeOwned(owned);}catch(rollback){error.rollbackCode=rollback.code||'FIXTURE_ROLLBACK_UNKNOWN';}throw error;}
 return {origin:`http://127.0.0.1:${server.address().port}`,udpPort:udpCanary.address().port,resetCanary(){canary=0;udpReceipts=0;tcpAccepts=0;for(const k of Object.keys(canaryCategories))canaryCategories[k]=0;},canaryCount(){return canary;},canaryCategories(){return {...canaryCategories,tcpAccepts,udpReceipts};},redirect(value){redirect=value;},slow(value){slow=value;},async close(){server.closeAllConnections();canaryServer.closeAllConnections();await Promise.all([new Promise(resolve=>udpCanary.close(resolve)),new Promise(resolve=>server.close(resolve)),new Promise(resolve=>canaryServer.close(resolve))]);}};
}
