import {fail,bounded} from './wire.mjs';
// The first inspection is read-only. Scrolling is explicitly requested only
// after all validation, and the target is inspected again before dispatch.
export function targetExpression(p,move=false){return `(()=>{const p=${JSON.stringify(p)};const node=p.ref?globalThis.__abwBoundSnapshot?.node(p.snapshotId,p.ref):document.querySelector(p.selector);if(!node||!node.isConnected||node.ownerDocument!==document)return {__abwError:'REF_STALE_OR_OWNER'};${move?"node.scrollIntoView({block:'center',inline:'nearest'});":''}const r=node.getBoundingClientRect();return {x:Math.max(1,Math.min(innerWidth-1,r.left+r.width/2)),y:Math.max(1,Math.min(innerHeight-1,r.top+r.height/2)),visible:r.width>0&&r.height>0,tag:node.tagName,type:node.type||'',href:node.href||null,download:node.hasAttribute('download'),form:!!node.form,disabled:!!node.disabled,readOnly:!!node.readOnly,sensitive:/password|secret|token|otp|credit|cardnumber|login/i.test([node.type,node.name,node.id,node.autocomplete].join(' ')),checked:!!node.checked,value:node.value??null,options:node.options?Array.from(node.options).map(o=>o.value).slice(0,100):null};})()`;}
const keys={Enter:[13,'Enter'],Tab:[9,'Tab'],Backspace:[8,'Backspace'],Delete:[46,'Delete'],Escape:[27,'Escape'],ArrowLeft:[37,'ArrowLeft'],ArrowUp:[38,'ArrowUp'],ArrowRight:[39,'ArrowRight'],ArrowDown:[40,'ArrowDown'],Home:[36,'Home'],End:[35,'End'],PageUp:[33,'PageUp'],PageDown:[34,'PageDown'],'Control+A':[65,'KeyA']};
export async function inputTool({name,p,resolve,cdp,read,active,deadline,fixture,allowPublicLink}){
 let actionsSent=0;const effects=[];
 const send=async(method,params)=>{actionsSent++;return cdp(method,params);};
 const inspect=async q=>{const t=await resolve(q,false);if(!t.visible)throw fail('INPUT_NOT_VISIBLE');if(t.frameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(t.disabled||t.sensitive||['password','file','hidden'].includes(t.type))throw fail('INPUT_RESTRICTED');return t;};
 const validate=async(kind,q,t)=>{if(t.frameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(kind==='text'){if(typeof q.text!=='string'||q.text.length>8192)throw fail('INVALID_INPUT');if(!['INPUT','TEXTAREA'].includes(t.tag)||['checkbox','radio','submit','button','image','file','password','hidden'].includes(t.type))throw fail('UNSUPPORTED_FIELD');if(t.readOnly)throw fail('INPUT_RESTRICTED');}else if(kind==='check'){if(t.type!=='checkbox'||typeof q.check!=='boolean')throw fail('UNSUPPORTED_FIELD');}else if(kind==='select'){if(t.tag!=='SELECT'||!t.options?.includes(q.value))throw fail('UNSUPPORTED_FIELD');}if(!fixture){if(q.submit||t.download||['submit','image'].includes(t.type))throw fail('PUBLIC_SUBMISSION_RESTRICTED');if(t.tag==='A'&&t.href)await allowPublicLink(t.href);}};
 const clickValidated=async(q,kind='click')=>{await validate(kind,q,await inspect(q));const t=await resolve(q,true);await validate(kind,q,t);if(t.disabled||t.sensitive||!t.visible)throw fail('INPUT_RESTRICTED');await send('Input.dispatchMouseEvent',{type:'mousePressed',x:t.x,y:t.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:t.x,y:t.y,button:'left',clickCount:1});return t;};
 const key=async k=>{const focus=await active();if(focus.frameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(!fixture&&(focus.sensitive||['password','file'].includes(focus.type)))throw fail('INPUT_RESTRICTED');if(!fixture&&k==='Enter'&&(focus.form||['submit','image','button'].includes(focus.type)||['INPUT','TEXTAREA','SELECT'].includes(focus.tag)))throw fail('PUBLIC_SUBMISSION_RESTRICTED');const spec=keys[k];const modifiers=k==='Control+A'?2:0,label=k==='Control+A'?'a':k;await send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:label,code:spec[1],windowsVirtualKeyCode:spec[0],nativeVirtualKeyCode:spec[0],modifiers});await send('Input.dispatchKeyEvent',{type:'keyUp',key:label,code:spec[1],windowsVirtualKeyCode:spec[0],nativeVirtualKeyCode:spec[0],modifiers});};
 const text=async q=>{await clickValidated(q,'text');if(q.clear!==false)await key('Control+A');const focused=await active();if(focused.frameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(focused.sensitive)throw fail('INPUT_RESTRICTED');await send('Input.insertText',{text:q.text});if(q.submit)await key('Enter');return {insertedCharacters:q.text.length};};
 try{
  if(!fixture&&p.submit)throw fail('PUBLIC_SUBMISSION_RESTRICTED');
  if(name==='key'){const list=Array.isArray(p.key)?p.key:[p.key];if(list.some(k=>!keys[k]))throw fail('UNSUPPORTED_KEY');const t=p.ref?await inspect(p):await active();if(t.frameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(!fixture&&(t.sensitive||['password','file'].includes(t.type)))throw fail('INPUT_RESTRICTED');if(!fixture&&list.includes('Enter')&&(t.form||['submit','image','button'].includes(t.type)||['INPUT','TEXTAREA','SELECT'].includes(t.tag)))throw fail('PUBLIC_SUBMISSION_RESTRICTED');if(p.ref)await clickValidated(p);for(let i=0;i<(p.repeat??1);i++)for(const k of list)await key(k);return {keysSent:list.length*(p.repeat??1),state:await read()};}
  if(name==='type'){await validate('text',p,await inspect(p));return {...await text(p),input:'browser insertText',state:await read()};}
  if(name==='fill'){const planned=[];for(const f of p.fields){const q={...f,snapshotId:f.snapshotId??p.snapshotId};const kinds=[f.text!==undefined?'text':null,f.check!==undefined?'check':null,f.value!==undefined?'select':null].filter(Boolean);if(kinds.length!==1)throw fail('INVALID_INPUT');const kind=kinds[0];await validate(kind,q,await inspect(q));planned.push({kind,q});}for(const {kind,q}of planned){await validate(kind,q,await inspect(q));if(kind==='text')effects.push(await text(q));else if(kind==='check'){const t=await inspect(q);if(t.checked!==q.check)await clickValidated(q,'check');effects.push({checked:q.check});}else{const t=await clickValidated(q,'select');await key('Home');for(let i=0;i<t.options.indexOf(q.value);i++)await key('ArrowDown');await key('Enter');effects.push({selectedValue:q.value});}}if(p.submit)await key('Enter');return {effects,input:'browser trusted input',state:await read()};}
  if(name==='click'){await clickValidated(p);return {clicked:true,input:'browser trusted mouse'};}
  if(name==='scroll'){for(let i=0;i<(p.times??1);i++){const focus=await active();if(focus.frameBlocked||focus.wheelFrameBlocked)throw fail('INPUT_FRAME_UNSUPPORTED');if(!fixture&&focus.sensitive)throw fail('INPUT_RESTRICTED');await send('Input.dispatchMouseEvent',{type:'mouseWheel',x:20,y:100,deltaX:0,deltaY:p.to==='top'?-1000:1000});if(p.wait)await bounded(new Promise(r=>setTimeout(r,p.wait)),deadline);}return {scrolled:true,state:await read()};}
  throw fail('UNSUPPORTED');
 }catch(e){e.data={...(e.data||{}),partial:actionsSent>0,actionsMayHaveRun:actionsSent>0,actionsRequested:actionsSent,effects};throw e;}
}
