import dns from 'node:dns/promises';import net from 'node:net';import {fail,bounded} from './wire.mjs';
export const DEFAULT_ORIGINS=null;
export function canonicalOrigin(input){if(typeof input!=='string'||!input||input.length>2048||input.trim()!==input||/[\\\s]/.test(input)||input.includes('*'))throw fail('INVALID_ORIGIN');let u;try{u=new URL(input);}catch{throw fail('INVALID_ORIGIN');}if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/'||(u.port&&Number(u.port)<1))throw fail('INVALID_ORIGIN');const host=u.hostname;if(net.isIP(host.replace(/^\[|\]$/g,''))||host.length>253||!host.includes('.')||host.endsWith('.')||!host.split('.').every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(x))||/\.(?:localhost|local|internal|lan|home|test|invalid)$/.test(host)||host==='localhost')throw fail('INVALID_ORIGIN');return u.origin;}
// null is the internal representation of the authorized default public HTTPS mode.
// An explicitly supplied array remains a bounded navigation/API business scope.
export function originsForTask(input){if(input===undefined||input===null)return null;if(!Array.isArray(input)||!input.length||input.length>8)throw fail('INVALID_ORIGINS');const origins=input.map(canonicalOrigin);if(new Set(origins).size!==origins.length)throw fail('DUPLICATE_ORIGIN');return Object.freeze(origins);}
export function public4(ip){const a=ip.split('.').map(Number);return a.length===4&&a.every(n=>n>=0&&n<=255)&&![0,10,127].includes(a[0])&&a[0]<224&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&a[1]===168)&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&[18,19].includes(a[1]))&&!(a[0]===192&&a[1]===0)&&!(a[0]===198&&a[1]===51&&a[2]===100)&&!(a[0]===203&&a[1]===0&&a[2]===113);}
export function public6(ip){if(net.isIP(ip)!==6)return false;const groups=ip.toLowerCase().split(':');const first=parseInt(groups[0]||'0',16),second=parseInt(groups[1]||'0',16);return first>=0x2000&&first<0x4000&&!(first===0x2001&&(second<0x0200||second===0x0db8))&&first!==0x2002&&first!==0x3fff;}
export function publicAddress(address){return net.isIP(address)===4?public4(address):public6(address);}
export async function publicOrigin(origin,deadline,lookup=dns.lookup){canonicalOrigin(origin);const u=new URL(origin);const addresses=await bounded(lookup(u.hostname,{all:true}),deadline,'DNS_UNKNOWN');if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw fail('DNS_NONPUBLIC');return true;}
export async function validateOrigins(origins,deadline){const normalized=originsForTask(origins);if(normalized)for(const origin of normalized)await publicOrigin(origin,deadline);return normalized;}
export function nativeScope(origins){return origins===null?'PUBLIC_HTTPS_V1':origins.join('\n');}
export async function allowedUrl(url,origins,fixture,deadline,lookup=dns.lookup){if(typeof url!=='string'||url.length>8192||url.includes('\\'))throw fail('URL_REJECTED');let u;try{u=new URL(url);}catch{throw fail('URL_REJECTED');}if(u.username||u.password)throw fail('URL_REJECTED');if(u.origin===fixture)return {kind:'synthetic',origin:u.origin};if(u.protocol!=='https:')throw fail('URL_REJECTED');canonicalOrigin(u.origin);if(origins!==null&&!origins.includes(u.origin))throw fail('ORIGIN_OUT_OF_SCOPE');await publicOrigin(u.origin,deadline,lookup);return {kind:'public-https',origin:u.origin,publicDns:true,mode:origins===null?'public-https':'explicit-top-navigation'};}
