// WP19-C isolated CLI: one HWND, one fresh Environment/default Profile, two real controllers.
#define NOMINMAX
#include <winsock2.h>
#include <windows.h>
#include "network-policy.h"
#include "document-request-permit.h"
#include <windowsx.h>
#include <commctrl.h>
#include "ui-design.h"
#include <shellapi.h>
#include <dcomp.h>
#include <dwmapi.h>
#include <wincodec.h>
#include <shlwapi.h>
#include <wrl.h>
#include <WebView2.h>
#include "resource-policy.h"
#include <WebView2EnvironmentOptions.h>
#include <array>
#include <atomic>
#include <filesystem>
#include <memory>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <thread>
#include <map>
#include <chrono>
#include "bounded-output.h"
#include <tuple>
#include <vector>
#include "ownership.h"
#include "limited-stream.h"
#include "startup-gate.h"
#include "min-window-contract.h"
#include "control-model.h"
#include "source-state.h"
#include "history-entry.h"
using Microsoft::WRL::ComPtr;using Microsoft::WRL::Callback;namespace fs=std::filesystem;
constexpr UINT commandMessage=WM_APP+31,captureTimer=61,closeTimer=62;
constexpr int backId=210,forwardId=211,reloadId=212,overviewId=201,pageAId=202,pageBId=203,pageBaseId=300,closePageId=209,takeoverId=204,confirmId=205,cancelId=206,returnId=207,refreshId=208,addressId=213;
constexpr COLORREF bg=ui::bg,panel=ui::panel,ink=ui::text,muted=ui::muted,accent=ui::accent;
std::timed_mutex outputMutex;std::atomic<bool> outputFailed{false};HWND outputWindow=nullptr;thread_local ULONGLONG eventDeadline=0;std::atomic<int> queuedCommands{0};
std::string utf8(const std::wstring&s){if(s.empty())return {};const int n=WideCharToMultiByte(CP_UTF8,0,s.data(),static_cast<int>(s.size()),nullptr,0,nullptr,nullptr);std::string out(n,'\0');WideCharToMultiByte(CP_UTF8,0,s.data(),static_cast<int>(s.size()),out.data(),n,nullptr,nullptr);return out;}
std::string json(const std::string&s){std::string out="\"";for(const unsigned char c:s){if(c=='"'||c=='\\'){out+='\\';out+=c;}else if(c<32)out+='?';else out+=c;}return out+'"';}
void emit(const std::string&s,ULONGLONG deadline=0){if(outputFailed)return;if(!deadline)deadline=eventDeadline?eventDeadline:GetTickCount64()+2000;std::unique_lock<std::timed_mutex> lock(outputMutex,std::defer_lock);const auto now=GetTickCount64();const bool locked=now<deadline&&lock.try_lock_for(std::chrono::milliseconds(deadline-now));const auto line=s+"\n";if(s.size()>131072||!locked||!outputUntil(GetStdHandle(STD_OUTPUT_HANDLE),line.data(),static_cast<DWORD>(line.size()),deadline)){outputFailed=true;if(outputWindow)PostMessage(outputWindow,WM_APP+32,0,0);}}

std::string hex16(FILETIME t){std::ostringstream o;o<<std::hex<<std::setfill('0')<<std::setw(8)<<t.dwHighDateTime<<std::setw(8)<<t.dwLowDateTime;return o.str();}
struct Command{std::uint64_t deadline=0;std::uint32_t id=0;std::string operation;int caller=-1,target=-1;std::string value;};
bool unsignedNumber(const std::string&s,unsigned&n){if(s.empty()||s.size()>9)return false;n=0;for(const auto c:s){if(c<'0'||c>'9')return false;n=n*10+static_cast<unsigned>(c-'0');}return true;}
bool safeValue(const std::string&s){return s.size()<=40&&s.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 _-")==std::string::npos;}
struct WindowRoles {int main=0,visibleAux=0;bool complete=true;std::vector<std::string> entries;};
BOOL CALLBACK classifyWindow(HWND window,LPARAM data){auto&roles=*reinterpret_cast<WindowRoles*>(data);DWORD pid=0;if(!GetWindowThreadProcessId(window,&pid)||pid!=GetCurrentProcessId())return TRUE;wchar_t type[128]{};RECT r{};DWORD cloaked=0;const bool classKnown=GetClassNameW(window,type,128)>0,rectKnown=GetWindowRect(window,&r)!=FALSE,cloakKnown=SUCCEEDED(DwmGetWindowAttribute(window,DWMWA_CLOAKED,&cloaked,sizeof(cloaked)));const auto style=GetWindowLongPtr(window,GWL_STYLE),extended=GetWindowLongPtr(window,GWL_EXSTYLE);const bool visible=IsWindowVisible(window)!=FALSE,parent=GetParent(window)!=nullptr,positive=rectKnown&&r.right>r.left&&r.bottom>r.top,main=classKnown&&wcscmp(type,L"AgentBrowserNativeSingleWindow")==0&&!parent&&positive&&visible&&cloakKnown&&cloaked==0&&(style&WS_OVERLAPPEDWINDOW)==WS_OVERLAPPEDWINDOW;
 if(main)roles.main++;else if(visible)roles.visibleAux++;if(!classKnown||!rectKnown||!cloakKnown)roles.complete=false;std::ostringstream o;o<<"{\"class\":"<<json(utf8(type))<<",\"visible\":"<<(visible?"true":"false")<<",\"parentPresent\":"<<(parent?"true":"false")<<",\"positiveRect\":"<<(positive?"true":"false")<<",\"cloakedKnown\":"<<(cloakKnown?"true":"false")<<",\"cloaked\":"<<(cloaked?"true":"false")<<",\"toolWindow\":"<<((extended&WS_EX_TOOLWINDOW)?"true":"false")<<",\"appWindow\":"<<((extended&WS_EX_APPWINDOW)?"true":"false")<<",\"userMainClass\":"<<(main?"true":"false")<<"}";roles.entries.push_back(o.str());return TRUE;}
std::string ownWindowRoles(){WindowRoles r;const bool ok=EnumWindows(classifyWindow,reinterpret_cast<LPARAM>(&r))!=FALSE;std::ostringstream o;o<<"{\"complete\":"<<((ok&&r.complete)?"true":"false")<<",\"mainClassCount\":"<<r.main<<",\"otherVisibleOwnWindows\":"<<r.visibleAux<<",\"humanTaskbarAcceptance\":\"unverified\",\"metadata\":[";for(size_t i=0;i<r.entries.size();i++){if(i)o<<',';o<<r.entries[i];}o<<"]}";return o.str();}
std::unique_ptr<Command> parseCommand(const std::string&line){std::vector<std::string> a;std::stringstream input(line);std::string word;while(std::getline(input,word,'\t'))a.push_back(word);if(a.size()<2||a.size()>6)return {};unsigned id=0;if(!unsignedNumber(a[0],id)||id==0)return {};auto c=std::make_unique<Command>();c->id=id;c->operation=a[1];
 unsigned budget=0;if(c->operation=="close"){if(a.size()!=3||!unsignedNumber(a[2],budget)||!budget||budget>25000)return {};c->deadline=GetTickCount64()+budget;return c;}
 if(a.size()<5||!unsignedNumber(a[4],budget)||!budget||budget>25000)return {};c->deadline=GetTickCount64()+budget;a.erase(a.begin()+4);
 if(a.size()<4||a[2].size()!=1||a[3].size()!=1||a[2][0]<'0'||a[2][0]>'1'||a[3][0]<'0'||a[3][0]>'7')return {};c->caller=a[2][0]-'0';c->target=a[3][0]-'0';
 if(c->operation=="mutate"){if(a.size()!=5||!safeValue(a[4]))return {};c->value=a[4];}
 else if(c->operation=="history"||c->operation=="register"||c->operation=="scope-check"||c->operation=="navigate"||c->operation=="script"||c->operation=="label"||c->operation=="cdp"){if(a.size()!=5||a[4].size()>120000||a[4].size()%2||a[4].find_first_not_of("0123456789abcdef")!=std::string::npos)return {};for(size_t i=0;i<a[4].size();i+=2)c->value+=static_cast<char>(std::stoi(a[4].substr(i,2),nullptr,16));}
 else if(a.size()!=4||!(c->operation=="page-new"||c->operation=="page-close"||c->operation=="input-begin"||c->operation=="input-expire-test"||c->operation=="input-end"||c->operation=="unregister"||c->operation=="register"||c->operation=="client-lost"||c->operation=="capture"||c->operation=="stats"||c->operation=="view"||c->operation=="overview"||c->operation=="request-takeover"||c->operation=="confirm"||c->operation=="cancel"||c->operation=="request-handback"||c->operation=="minimize"||c->operation=="restore"||c->operation=="human-back"||c->operation=="human-forward"||c->operation=="human-reload"))return {};
 return c;
}
struct Page {
 network::DocumentRequestPermit topDocumentPermit;
 // History entry identity is independent of SDK NavigationId (unchanged for a
 // same-document traversal). All callbacks remain tied to this pending request.
 std::string navigationAction;std::wstring navigationTarget;int navigationEntry=0;bool navigationInvoked=false,navigationVerifying=false;std::uint64_t navigationLifetime=0,sourceEvents=0,historyEvents=0;unsigned navigationGeneration=0;
 std::uint64_t lifetime=0;bool urlKnown=false;bool active=false;unsigned createRequest=0;std::uint64_t createEpoch=0,createDeadline=0;bool inputOperation=false,mouseHeld=false;std::vector<unsigned> keysHeld;std::uint64_t inputEpoch=0,inputDocument=0,inputLifetime=0,inputDeadline=0;IUnknown* inputIdentity=nullptr;std::wstring agentLabel=L"等待 Agent",taskLabel=L"未注册任务";unsigned navigationRequest=0;std::uint64_t navigationEpoch=0,navigationDocument=0,navigationId=0,navigationDeadline=0;IUnknown* navigationController=nullptr;bool navigationBlocked=false,navigationHuman=false;unsigned scopeGeneration=0;
 ComPtr<ICoreWebView2CompositionController> composition;ComPtr<ICoreWebView2Controller> controller;ComPtr<ICoreWebView2Controller3> scale;ComPtr<ICoreWebView2> core;ComPtr<IDCompositionVisual> visual;
 std::wstring url,title,profile,profilePath;bool profileVerified=false,loaded=false,scriptPending=false;std::uint64_t document=0,geometry=0,sequence=0;std::string lastPng,lastStats="null";std::vector<unsigned char> thumbnail;std::uint32_t revision=0;
};
struct Capture {int page=0;std::uint32_t request=0;std::uint64_t document=0,geometry=0,epoch=0,sequence=0,deadline=0,presentation=0;IUnknown* controller=nullptr;bool active=true,minimized=false;min_window::Snapshot baseline{};ComPtr<LimitedStream> stream;};
class Host:public std::enable_shared_from_this<Host>{
public:
 std::map<unsigned,ULONGLONG> requestDeadlines;
 unsigned proxyPort=0;
 HWND window=nullptr,cover=nullptr;HFONT font=nullptr,largeFont=nullptr,smallFont=nullptr,pageFont=nullptr,iconFont=nullptr;UINT dpi=96;ui::Layout chrome{};HWND tooltip=nullptr,address=nullptr;std::wstring lastAddress,tooltipText;ComPtr<IDCompositionRectangleClip> guestClip;std::map<HWND,ui::Fade> fades;bool uiTimer=false;unsigned uiTicks=0,uiStarts=0,uiStops=0;std::wstring origin,udf;std::shared_ptr<owned::Directories> directories;std::array<Page,8> pages;network::Policy policy;demo::Controls controls;RECT bounds{};ComPtr<ICoreWebView2Controller> workerGuardController;ComPtr<ICoreWebView2> workerGuardCore;ComPtr<ICoreWebView2Environment> environment;ComPtr<IDCompositionDevice> device;ComPtr<IDCompositionTarget> target;ComPtr<IDCompositionVisual> root;
 struct RetiredBrowser {HANDLE handle;DWORD pid;std::string creation;};std::vector<RetiredBrowser> retiredBrowsers;std::uint64_t retiredVerifiedExits=0;HANDLE browser=nullptr;DWORD browserPid=0;std::string browserCreation,runtime,status="starting",error="NONE";bool closing=false,environmentInvoked=false,released=false,mouseCaptured=false,captureUncertain=false;int deniedWorkerResources=0;int deniedResources=0,deniedNavigations=0,deniedFrames=0,deniedPermissions=0,deniedDownloads=0,deniedWindows=0;int historyQueries=0,creationPending=0,shows=0,focusEvents=0,restoreEvents=0;std::uint64_t presentation=1,closeDeadline=0;std::shared_ptr<Capture> pending;int inputPage=-1;std::uint64_t inputEpoch=0,inputDocument=0,inputLifetime=0,inputDeadline=0;IUnknown* inputController=nullptr;
 ~Host(){if(browser)CloseHandle(browser);for(const auto&r:retiredBrowsers)CloseHandle(r.handle);if(font)DeleteObject(font);if(largeFont)DeleteObject(largeFont);if(smallFont)DeleteObject(smallFont);if(pageFont)DeleteObject(pageFont);if(iconFont)DeleteObject(iconFont);}
 bool check(HRESULT hr,const char*code){if(SUCCEEDED(hr))return true;if(error=="NONE")error=code;status="failed";controls.failClosed();if(pending)pending->active=false;resetInputCapture();record();return false;}
 void result(unsigned id,bool ok,const char*code,const std::string&data="null"){const auto found=requestDeadlines.find(id);const auto deadline=found==requestDeadlines.end()?GetTickCount64()+2000:found->second;emit("{\"kind\":\"result\",\"id\":"+std::to_string(id)+",\"ok\":"+(ok?"true":"false")+",\"code\":"+json(code)+",\"data\":"+data+"}",deadline);requestDeadlines.erase(id);}
 void record(){if(!directories)return;syncAddress();std::ostringstream o;o<<"{\"status\":"<<json(status)<<",\"error\":"<<json(error)<<",\"hostPid\":"<<GetCurrentProcessId()<<",\"hwnd\":"<<reinterpret_cast<std::uintptr_t>(window)<<",\"browserPid\":"<<browserPid<<",\"browserCreationHex\":"<<json(browserCreation)<<",\"retiredBrowserCount\":"<<(retiredBrowsers.size()+retiredVerifiedExits)<<",\"retiredBrowsersExited\":"<<([this](){bool ended=true;for(const auto&r:retiredBrowsers)ended=ended&&WaitForSingleObject(r.handle,0)==WAIT_OBJECT_0;return ended; }()?"true":"false")<<",\"runtime\":"<<json(runtime)<<",\"sharedEnvironment\":true,\"sharedDefaultProfile\":"<<(pages[0].profileVerified?"true":"false")<<",\"environmentIdentity\":"<<reinterpret_cast<std::uintptr_t>(environment.Get())<<",\"selected\":"<<controls.selected<<",\"viewing\":"<<(controls.viewing?"true":"false")<<",\"pendingConfirmation\":"<<static_cast<int>(controls.pending)<<",\"iconic\":"<<(IsIconic(window)?"true":"false")<<",\"showEvents\":"<<shows<<",\"focusEvents\":"<<focusEvents<<",\"restoreEvents\":"<<restoreEvents<<",\"capturePending\":"<<(pending?"true":"false")<<",\"captureUncertain\":"<<(captureUncertain?"true":"false")<<",\"creationPending\":"<<creationPending<<",\"pages\":[";
  for(int i=0;i<8;i++){if(i)o<<',';const auto&p=pages[i];const auto&t=controls.tasks[demo::owner(i)];o<<"{\"agentId\":"<<json("owner-slot-"+std::to_string(demo::owner(i)))<<",\"taskId\":"<<json("task-slot-"+std::to_string(demo::owner(i)))<<",\"pageId\":"<<json("page-slot-"+std::to_string(i))<<",\"active\":"<<(p.active?"true":"false")<<",\"ownerSlot\":"<<demo::owner(i)<<",\"pageSlot\":"<<i<<",\"registered\":"<<(t.registered?"true":"false")<<",\"paused\":"<<(t.paused?"true":"false")<<",\"human\":"<<(t.human?"true":"false")<<",\"epoch\":"<<t.epoch<<",\"loaded\":"<<(p.loaded?"true":"false")<<",\"document\":"<<p.document<<",\"geometry\":"<<p.geometry<<",\"controllerIdentity\":"<<reinterpret_cast<std::uintptr_t>(p.controller.Get())<<",\"profileName\":"<<json(utf8(p.profile))<<",\"profilePath\":"<<json(utf8(p.profilePath))<<",\"lifetime\":"<<p.lifetime<<",\"urlKnown\":"<<(p.urlKnown?"true":"false")<<",\"url\":"<<json(utf8(p.url))<<",\"title\":"<<json(utf8(p.title))<<",\"inputOperation\":"<<(p.inputOperation?"true":"false")<<",\"navigationPending\":"<<(p.navigationRequest?"true":"false")<<",\"navigationId\":"<<p.navigationId<<",\"sourceEvents\":"<<p.sourceEvents<<",\"historyEvents\":"<<p.historyEvents<<",\"scriptPending\":"<<(p.scriptPending?"true":"false")<<",\"png\":"<<json(p.lastPng)<<",\"lastStats\":"<<p.lastStats<<"}";}
  o<<"],\"uiEffects\":{\"timerActive\":"<<(uiTimer?"true":"false")<<",\"motionAllowed\":"<<(motionAllowed()?"true":"false")<<",\"ticks\":"<<uiTicks<<",\"starts\":"<<uiStarts<<",\"stops\":"<<uiStops<<",\"radius\":"<<ui::px(ui::containerRadius,dpi)<<",\"guest\":["<<bounds.left<<","<<bounds.top<<","<<bounds.right<<","<<bounds.bottom<<"]},\"proxyPort\":"<<proxyPort<<",\"networkDenials\":{\"resources\":"<<deniedResources<<",\"navigations\":"<<deniedNavigations<<",\"frames\":"<<deniedFrames<<",\"workers\":"<<deniedWorkerResources<<",\"permissions\":"<<deniedPermissions<<",\"downloads\":"<<deniedDownloads<<",\"windows\":"<<deniedWindows<<"},\"ownWindowRoles\":"<<ownWindowRoles()<<"}";directories->writeState(o.str());emit("{\"kind\":\"state\",\"data\":"+o.str()+"}");if(cover)InvalidateRect(cover,nullptr,TRUE);if(window){for(int i=0;i<8;i++)InvalidateRect(GetDlgItem(window,pageBaseId+i),nullptr,TRUE);InvalidateRect(window,nullptr,FALSE);}
 }
 min_window::Snapshot snapshot()const{const HWND f=GetForegroundWindow();DWORD pid=0;const bool known=!f||GetWindowThreadProcessId(f,&pid)!=0;return {IsIconic(window)!=FALSE,known,f==window,f&&known&&pid==GetCurrentProcessId(),shows,focusEvents,restoreEvents};}
 bool allowed(int page,const std::wstring&url){return policy.allowed(demo::owner(page),url);}

 std::wstring wide(const std::string&v){const int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,v.data(),static_cast<int>(v.size()),nullptr,0);if(n<=0)return {};std::wstring out(n,L'\0');MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,v.data(),static_cast<int>(v.size()),out.data(),n);return out;}
 bool identify(ICoreWebView2*view){UINT32 pid=0;if(!view||FAILED(view->get_BrowserProcessId(&pid))||!pid)return check(E_FAIL,"BROWSER_IDENTITY");if(browser&&pid==browserPid)return true;if(browser){for(auto it=retiredBrowsers.begin();it!=retiredBrowsers.end();){if(WaitForSingleObject(it->handle,0)==WAIT_OBJECT_0){CloseHandle(it->handle);it=retiredBrowsers.erase(it);retiredVerifiedExits++;}else ++it;}if(retiredBrowsers.size()>=8)return check(E_FAIL,"BROWSER_TRANSITION_LIMIT");for(const auto&p:pages)if(p.core&&p.core.Get()!=view){UINT32 other=0;if(FAILED(p.core->get_BrowserProcessId(&other))||other!=pid)return check(E_FAIL,"SHARED_BROWSER_MISMATCH");}retiredBrowsers.push_back({browser,browserPid,browserCreation});browser=nullptr;}browserPid=pid;browser=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION|SYNCHRONIZE,FALSE,pid);FILETIME c{},e{},k{},u{};if(!browser||!GetProcessTimes(browser,&c,&e,&k,&u))return check(E_FAIL,"BROWSER_HANDLE");browserCreation=hex16(c);return true;}
 bool motionAllowed()const{BOOL enabled=TRUE;SystemParametersInfoW(SPI_GETCLIENTAREAANIMATION,0,&enabled,0);return ui::allowMotion(enabled!=FALSE,IsIconic(window)!=FALSE,GetForegroundWindow()==window,closing);}
 void stopFeedback(){if(uiTimer)uiStops++;KillTimer(window,73);uiTimer=false;for(auto&entry:fades){auto&f=entry.second;if(f.active){f.active=false;f.current=f.to;InvalidateRect(entry.first,nullptr,FALSE);}}}
 COLORREF feedback(HWND hwnd,COLORREF fillTarget,unsigned duration){auto it=fades.find(hwnd);if(it==fades.end()){ui::Fade f;f.from=f.to=f.current=fillTarget;fades.emplace(hwnd,f);return fillTarget;}auto&f=it->second;if(!motionAllowed()){f.active=false;f.current=f.from=f.to=fillTarget;return fillTarget;}if(f.to!=fillTarget){f.from=f.current;f.to=fillTarget;f.start=GetTickCount64();uiStarts++;f.duration=duration;f.active=true;if(!uiTimer){uiTimer=SetTimer(window,73,16,nullptr)!=0;if(!uiTimer){f.active=false;f.current=fillTarget;}}}return f.active?f.tick(GetTickCount64()):f.current;}
 void tickFeedback(){if(!motionAllowed()){stopFeedback();return;}bool any=false;uiTicks++;for(auto&entry:fades){auto&f=entry.second;if(f.active){f.tick(GetTickCount64());InvalidateRect(entry.first,nullptr,FALSE);any=any||f.active;}}if(!any){KillTimer(window,73);uiTimer=false;}}
 const wchar_t* taskState(int n)const{const auto&t=controls.tasks[demo::owner(n)];if(controls.pending!=demo::Pending::none&&demo::owner(controls.selected)==demo::owner(n))return L"等待确认";return t.human?L"你在操作":t.paused?L"Agent 已暂停":L"只读查看";}
 void syncAddress(){if(!address)return;const auto&p=pages[controls.selected];const auto value=p.urlKnown?p.url:L"等待网页";if(value!=lastAddress){lastAddress=value;SetWindowTextW(address,value.c_str());}}
 void setFonts(UINT value){dpi=value?value:96;auto create=[&](int size,int weight,const wchar_t*name){return CreateFontW(-ui::px(size,dpi),0,0,0,weight,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,name);};for(auto f:{font,largeFont,smallFont,pageFont,iconFont})if(f)DeleteObject(f);font=create(14,FW_NORMAL,L"Segoe UI");largeFont=create(20,FW_MEDIUM,L"Segoe UI");smallFont=create(11,FW_NORMAL,L"Segoe UI");pageFont=create(12,FW_NORMAL,L"Segoe UI");iconFont=create(20,FW_NORMAL,L"Segoe MDL2 Assets");for(int id:{backId,forwardId,reloadId,overviewId,takeoverId,returnId,refreshId,closePageId,confirmId,cancelId})SendMessage(GetDlgItem(window,id),WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);for(int i=0;i<8;i++)SendMessage(GetDlgItem(window,pageBaseId+i),WM_SETFONT,reinterpret_cast<WPARAM>(font),TRUE);SendMessage(address,WM_SETFONT,reinterpret_cast<WPARAM>(pageFont),TRUE);}
 void arrange(){RECT client{};GetClientRect(window,&client);std::array<bool,8> active{};for(int i=0;i<8;i++)active[i]=pages[i].active;chrome=ui::calculate(client.right,client.bottom,dpi,active,controls.pending!=demo::Pending::none);const std::array<int,10> ids={backId,forwardId,reloadId,overviewId,takeoverId,returnId,refreshId,closePageId,confirmId,cancelId};for(size_t i=0;i<ids.size();i++){const auto&r=chrome.buttons[i];MoveWindow(GetDlgItem(window,ids[i]),r.left,r.top,r.right-r.left,r.bottom-r.top,TRUE);}for(int i=0;i<8;i++){const auto&r=chrome.pages[i];MoveWindow(GetDlgItem(window,pageBaseId+i),r.left,r.top,r.right-r.left,r.bottom-r.top,TRUE);const auto caption=(pages[i].title.empty()?std::wstring(L"网页加载中"):pages[i].title)+L" · "+taskState(i);SetWindowTextW(GetDlgItem(window,pageBaseId+i),caption.c_str());}const auto&a=chrome.address;MoveWindow(address,a.left+ui::px(10,dpi),a.top+ui::px(7,dpi),a.right-a.left-ui::px(20,dpi),a.bottom-a.top-ui::px(14,dpi),TRUE);syncAddress();}
 void layout(){
  if(IsIconic(window)||error!="NONE")return;arrange();if(!device)return;RECT next=chrome.guest;if(memcmp(&next,&bounds,sizeof(RECT)))resetInputCapture();if(next.right-next.left<100||next.bottom-next.top<100)return;
  for(auto&p:pages)if(p.controller){RECT actual{};if(!check(p.controller->put_Bounds(next),"BOUNDS_SET")||!check(p.controller->get_Bounds(&actual),"BOUNDS_READ")||memcmp(&actual,&next,sizeof(RECT))){check(E_FAIL,"BOUNDS_MISMATCH");return;}}
  if(!guestClip&&!check(device->CreateRectangleClip(&guestClip),"ROUND_CLIP_CREATE"))return;const float width=static_cast<float>(next.right-next.left),height=static_cast<float>(next.bottom-next.top),radius=static_cast<float>(ui::px(ui::containerRadius,dpi));if(!check(guestClip->SetLeft(0.0f),"CLIP_LEFT")||!check(guestClip->SetTop(0.0f),"CLIP_TOP")||!check(guestClip->SetRight(width),"CLIP_RIGHT")||!check(guestClip->SetBottom(height),"CLIP_BOTTOM"))return;for(auto hr:{guestClip->SetTopLeftRadiusX(radius),guestClip->SetTopLeftRadiusY(radius),guestClip->SetTopRightRadiusX(radius),guestClip->SetTopRightRadiusY(radius),guestClip->SetBottomLeftRadiusX(radius),guestClip->SetBottomLeftRadiusY(radius),guestClip->SetBottomRightRadiusX(radius),guestClip->SetBottomRightRadiusY(radius)})if(!check(hr,"CLIP_RADIUS"))return;if(!check(root->SetOffsetX(static_cast<float>(next.left)),"VISUAL_X")||!check(root->SetOffsetY(static_cast<float>(next.top)),"VISUAL_Y")||!check(root->SetClip(guestClip.Get()),"VISUAL_CLIP")||!check(device->Commit(),"LAYOUT_COMMIT"))return;
  const bool changed=memcmp(&next,&bounds,sizeof(RECT))!=0;bounds=next;for(auto&p:pages)if(p.controller&&(changed||p.geometry==0))p.geometry++;if(cover&&!MoveWindow(cover,bounds.left,bounds.top,bounds.right-bounds.left,bounds.bottom-bounds.top,TRUE)){check(E_FAIL,"COVER_LAYOUT");return;}if(cover){const int round=ui::px(ui::containerRadius*2,dpi);auto region=CreateRoundRectRgn(0,0,bounds.right-bounds.left+1,bounds.bottom-bounds.top+1,round,round);if(!region||!SetWindowRgn(cover,region,TRUE)){if(region)DeleteObject(region);check(E_FAIL,"COVER_ROUND_CLIP");return;}}record();
 }
 void present(){if(!root||error!="NONE")return;resetInputCapture();auto&selected=pages[controls.selected];if(selected.visual){if(!check(root->RemoveAllVisuals(),"VIEW_REMOVE")||!check(root->AddVisual(selected.visual.Get(),FALSE,nullptr),"VIEW_ATTACH")||!check(device->Commit(),"VIEW_COMMIT"))return;}presentation++;ShowWindow(cover,controls.viewing?SW_HIDE:SW_SHOW);if(!controls.tasks[demo::owner(controls.selected)].human||controls.pending!=demo::Pending::none)SetFocus(window);updateButtons();record();}
 bool refreshSource(int index){auto&p=pages[index];LPWSTR source=nullptr;const auto hr=p.core->get_Source(&source);const bool ok=source_state::accept(hr,source,p.url,p.urlKnown);if(source)CoTaskMemFree(source);if(!ok){p.loaded=false;check(FAILED(hr)?hr:E_FAIL,"SOURCE_READ_UNKNOWN");}return ok;}
 bool navigationBinding(int index)const{const auto&p=pages[index];const auto&t=controls.tasks[demo::owner(index)];return !closing&&p.active&&p.core&&t.registered&&(p.navigationHuman?(t.paused&&t.human):(!t.paused&&!t.human))&&t.epoch==p.navigationEpoch&&p.controller.Get()==p.navigationController&&p.lifetime==p.navigationLifetime&&p.scopeGeneration==p.navigationGeneration&&policy.generations[demo::owner(index)]==p.navigationGeneration&&p.document==p.navigationDocument&&GetTickCount64()<p.navigationDeadline;}
 void finishSameDocument(int index){auto&p=pages[index];const auto id=p.navigationRequest;const bool same=navigationBinding(index)&&p.loaded&&p.urlKnown&&!p.navigationBlocked&&allowed(index,p.url);const auto data="{\"url\":"+json(p.urlKnown?utf8(p.url):"")+",\"webError\":0,\"navigationKind\":\"same-document\",\"historyEntryId\":"+std::to_string(p.navigationEntry)+"}";p.navigationRequest=0;p.navigationAction.clear();result(id,same,same?"NAVIGATED":"NAVIGATION_STALE",data);updateButtons();record();}
 void verifyHistoryEntry(int index){auto&p=pages[index];if(!p.navigationRequest||!p.navigationInvoked||p.navigationVerifying||p.navigationId||!p.loaded||!(p.navigationAction=="back"||p.navigationAction=="forward"))return;const auto id=p.navigationRequest;const auto lifetime=p.lifetime;const auto controller=p.controller.Get();p.navigationVerifying=true;auto weak=weak_from_this();
  historyQueries++;const auto hr=p.core->CallDevToolsProtocolMethod(L"Page.getNavigationHistory",L"{}",Callback<ICoreWebView2CallDevToolsProtocolMethodCompletedHandler>([weak,index,id,lifetime,controller](HRESULT hr,LPCWSTR data)->HRESULT{if(auto s=weak.lock()){s->historyQueries--;auto&p=s->pages[index];if(p.navigationRequest!=id||p.lifetime!=lifetime||p.controller.Get()!=controller)return S_OK;p.navigationVerifying=false;if(p.navigationId)return S_OK;history_entry::Snapshot history;if(FAILED(hr)||!history_entry::parse(data,history)||!s->navigationBinding(index)){p.navigationRequest=0;s->result(id,false,"HISTORY_RESULT_UNKNOWN");s->record();return S_OK;}if(history.ids[history.index]==p.navigationEntry&&s->refreshSource(index))s->finishSameDocument(index);}return S_OK;}).Get());if(FAILED(hr)){historyQueries--;p.navigationVerifying=false;p.navigationRequest=0;result(id,false,"HISTORY_QUERY_FAILED");}record();
 }
 void beginHistory(int page,unsigned request,const std::string&action,ULONGLONG deadline,bool human=false){auto&p=pages[page];if(!p.active||!p.core||!p.loaded||!p.urlKnown||ownerBusy(demo::owner(page))){if(request)result(request,false,"PAGE_BUSY");return;}BOOL available=TRUE;if(action=="back"){if(!check(p.core->get_CanGoBack(&available),"BACK_STATE_READ"))return;}else if(action=="forward"){if(!check(p.core->get_CanGoForward(&available),"FORWARD_STATE_READ"))return;}else if(action!="reload"){if(request)result(request,false,"UNSUPPORTED");return;}if(!available){if(request)result(request,false,"HISTORY_EMPTY");return;}if(!allowed(page,p.url)){if(request)result(request,false,"ORIGIN_OUT_OF_SCOPE");return;}
  const auto id=request?request:900000000u+static_cast<unsigned>(page);requestDeadlines[id]=deadline;p.navigationRequest=id;p.navigationEpoch=controls.tasks[demo::owner(page)].epoch;p.navigationController=p.controller.Get();p.navigationLifetime=p.lifetime;p.navigationGeneration=p.scopeGeneration;p.navigationDeadline=deadline;p.navigationHuman=human;p.navigationId=0;p.navigationBlocked=false;p.navigationAction=action;p.navigationEntry=0;p.navigationVerifying=false;p.navigationInvoked=false;p.document++;p.navigationDocument=p.document;
  if(action=="reload"){p.navigationInvoked=true;const auto hr=p.core->Reload();if(FAILED(hr)){p.navigationRequest=0;result(id,false,"HISTORY_CALL_FAILED");}record();return;}
  const auto lifetime=p.lifetime;const auto controller=p.controller.Get();auto weak=weak_from_this();historyQueries++;const auto hr=p.core->CallDevToolsProtocolMethod(L"Page.getNavigationHistory",L"{}",Callback<ICoreWebView2CallDevToolsProtocolMethodCompletedHandler>([weak,page,id,lifetime,controller,action](HRESULT hr,LPCWSTR data)->HRESULT{if(auto s=weak.lock()){s->historyQueries--;auto&p=s->pages[page];if(p.navigationRequest!=id||p.lifetime!=lifetime||p.controller.Get()!=controller)return S_OK;history_entry::Snapshot history;if(FAILED(hr)||!history_entry::parse(data,history)||!s->navigationBinding(page)||p.navigationId){p.navigationRequest=0;s->result(id,false,"HISTORY_QUERY_UNKNOWN");s->record();return S_OK;}const auto target=history.index+(action=="back"?-1:1);if(target<0||static_cast<size_t>(target)>=history.ids.size()){p.navigationRequest=0;s->result(id,false,"HISTORY_EMPTY");s->record();return S_OK;}p.navigationEntry=history.ids[target];p.navigationInvoked=true;const auto call=action=="back"?p.core->GoBack():p.core->GoForward();if(FAILED(call)){p.navigationRequest=0;s->result(id,false,"HISTORY_CALL_FAILED");}s->record();}return S_OK;}).Get());if(FAILED(hr)){historyQueries--;p.navigationRequest=0;result(id,false,"HISTORY_QUERY_FAILED");}record();
 }
 bool ownerBusy(int owner)const{for(int i=owner*4;i<owner*4+4;i++)if(pages[i].createRequest||pages[i].navigationRequest||pages[i].scriptPending||pages[i].inputOperation||(pending&&pending->page==i))return true;return false;}
 void updateButtons(){const bool ask=controls.pending!=demo::Pending::none;ShowWindow(GetDlgItem(window,confirmId),ask?SW_SHOW:SW_HIDE);ShowWindow(GetDlgItem(window,cancelId),ask?SW_SHOW:SW_HIDE);ShowWindow(GetDlgItem(window,takeoverId),controls.tasks[demo::owner(controls.selected)].human?SW_HIDE:SW_SHOW);ShowWindow(GetDlgItem(window,returnId),controls.tasks[demo::owner(controls.selected)].human?SW_SHOW:SW_HIDE);const int owner=demo::owner(controls.selected);EnableWindow(GetDlgItem(window,confirmId),!ownerBusy(owner));EnableWindow(GetDlgItem(window,takeoverId),controls.viewing&&pages[controls.selected].active&&!controls.tasks[owner].human&&!ask);EnableWindow(GetDlgItem(window,returnId),controls.tasks[owner].human&&!ask);for(int i=0;i<8;i++)ShowWindow(GetDlgItem(window,pageBaseId+i),pages[i].active?SW_SHOW:SW_HIDE);BOOL back=FALSE,forward=FALSE;const auto&shown=pages[controls.selected];if(shown.core){shown.core->get_CanGoBack(&back);shown.core->get_CanGoForward(&forward);}const bool historyReady=controls.viewing&&shown.active&&controls.tasks[owner].human&&!ownerBusy(owner);EnableWindow(GetDlgItem(window,backId),historyReady&&back);EnableWindow(GetDlgItem(window,forwardId),historyReady&&forward);EnableWindow(GetDlgItem(window,reloadId),historyReady);EnableWindow(GetDlgItem(window,closePageId),controls.viewing&&pages[controls.selected].active&&!ownerBusy(owner)&&!ask);layout();}
 void closePage(int page,unsigned request=0){auto&p=pages[page];if(ownerBusy(demo::owner(page))){if(request)result(request,false,"PAGE_BUSY");return;}p.lifetime++;if(p.composition)p.composition->put_RootVisualTarget(nullptr);if(p.controller&&!check(p.controller->Close(),"PAGE_CLOSE"))return;p.core.Reset();p.scale.Reset();p.controller.Reset();p.composition.Reset();p.loaded=false;p.active=false;p.document++;p.thumbnail.clear();p.url=origin+(demo::owner(page)?L"/agent-b":L"/agent-a");p.urlKnown=false;p.title.clear();p.lastPng.clear();p.lastStats="null";p.inputOperation=false;p.mouseHeld=false;p.keysHeld.clear();p.inputIdentity=nullptr;controls.active[page]=false;if(controls.selected==page){controls.viewing=false;auto&t=controls.tasks[demo::owner(page)];if(t.human){t.human=false;t.paused=false;t.epoch++;}controls.pending=demo::Pending::none;}if(request)result(request,true,"PAGE_CLOSED");present();}
 void ui(int id){if(closing||error!="NONE")return;bool changed=false;if(id>=pageBaseId&&id<pageBaseId+8)changed=controls.select(id-pageBaseId);else if(id==overviewId)changed=controls.overview();else if(id==takeoverId)changed=controls.requestTakeover();else if(id==returnId)changed=controls.requestHandback();else if(id==cancelId){controls.cancel();changed=true;}else if(id==confirmId)changed=controls.confirm(ownerBusy(demo::owner(controls.selected)));else if(id==backId||id==forwardId||id==reloadId){if(!controls.tasks[demo::owner(controls.selected)].human||!controls.viewing)return;beginHistory(controls.selected,0,id==backId?"back":id==forwardId?"forward":"reload",GetTickCount64()+15000,true);return;}else if(id==closePageId){closePage(controls.selected);return;}else if(id==refreshId){capture(controls.selected,0);return;}if(changed)present();}
 void initialize(){if(!check(DCompositionCreateDevice(nullptr,IID_PPV_ARGS(&device)),"DCOMP"))return;if(!check(device->CreateTargetForHwnd(window,FALSE,&target),"TARGET")||!check(device->CreateVisual(&root),"ROOT"))return;if(!check(target->SetRoot(root.Get()),"ROOT_TARGET"))return;for(auto&p:pages){if(!check(device->CreateVisual(&p.visual),"PAGE_VISUAL"))return;}if(!check(device->Commit(),"DCOMP_COMMIT"))return;auto opts=Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();if(!opts||!check(opts->put_AllowSingleSignOnUsingOSPrimaryAccount(FALSE),"SSO_DISABLED"))return;const std::wstring proxyArgs=L"--proxy-server=http://127.0.0.1:"+std::to_wstring(proxyPort)+L" --proxy-bypass-list=<-loopback> --disable-quic --webrtc-ip-handling-policy=disable_non_proxied_udp";if(!proxyPort||!check(opts->put_AdditionalBrowserArguments(proxyArgs.c_str()),"PROXY_OPTIONS"))return;ComPtr<ICoreWebView2EnvironmentOptions7> channels;if(!check(opts.As(&channels),"STABLE_OPTIONS"))return;if(!check(channels->put_ReleaseChannels(COREWEBVIEW2_RELEASE_CHANNELS_STABLE),"STABLE_CHANNEL")||!check(channels->put_ChannelSearchKind(COREWEBVIEW2_CHANNEL_SEARCH_KIND_MOST_STABLE),"STABLE_ORDER"))return;creationPending++;environmentInvoked=true;auto self=shared_from_this();
  const auto hr=CreateCoreWebView2EnvironmentWithOptions(nullptr,udf.c_str(),opts.Get(),Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>([self](HRESULT hr,ICoreWebView2Environment*env)->HRESULT{self->creationPending--;if(!self->check(hr,"ENVIRONMENT")||!env)return S_OK;self->environment=env;if(self->closing)return S_OK;ComPtr<ICoreWebView2Environment7> e7;LPWSTR actual=nullptr;if(!self->check(env->QueryInterface(IID_PPV_ARGS(&e7)),"UDF_INTERFACE")||!self->check(e7->get_UserDataFolder(&actual),"UDF_READ"))return S_OK;HANDLE folder=owned::openDirectory(actual?fs::path(actual):fs::path());if(actual)CoTaskMemFree(actual);const bool same=owned::plain(folder,self->udf);if(folder!=INVALID_HANDLE_VALUE)CloseHandle(folder);if(!same){self->check(E_FAIL,"UDF_MISMATCH");return S_OK;}LPWSTR version=nullptr;env->get_BrowserVersionString(&version);if(version){self->runtime=utf8(version);CoTaskMemFree(version);}self->createWorkerGuard();return S_OK;}).Get());if(FAILED(hr))creationPending--;check(hr,"ENVIRONMENT_CALL");
 }
 void createWorkerGuard(){creationPending++;auto self=shared_from_this();const auto hr=environment->CreateCoreWebView2Controller(window,Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>([self](HRESULT hr,ICoreWebView2Controller*controller)->HRESULT{self->creationPending--;if(self->closing){if(controller)controller->Close();return S_OK;}if(!self->check(hr,"WORKER_GUARD_CREATE")||!controller)return S_OK;self->workerGuardController=controller;if(!self->check(controller->put_IsVisible(FALSE),"WORKER_GUARD_HIDDEN")||!self->check(controller->get_CoreWebView2(&self->workerGuardCore),"WORKER_GUARD_CORE")||!self->identify(self->workerGuardCore.Get()))return S_OK;ComPtr<ICoreWebView2_22> networkCore;if(!self->check(self->workerGuardCore.As(&networkCore),"WORKER_FILTER_INTERFACE")||!self->check(networkCore->AddWebResourceRequestedFilterWithRequestSourceKinds(L"*",COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL,static_cast<COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS>(COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER|COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER)),"WORKER_FILTER"))return S_OK;auto weak=self->weak_from_this();EventRegistrationToken token{};self->check(self->workerGuardCore->add_WebResourceRequested(Callback<ICoreWebView2WebResourceRequestedEventHandler>([weak](ICoreWebView2*,ICoreWebView2WebResourceRequestedEventArgs*a)->HRESULT{if(auto s=weak.lock()){ComPtr<ICoreWebView2WebResourceResponse> response;s->deniedWorkerResources++;if(!s->check(s->environment->CreateWebResourceResponse(nullptr,403,L"Worker network unsupported",L"Content-Type: text/plain",&response),"WORKER_DENY_CREATE")||!s->check(a->put_Response(response.Get()),"WORKER_DENY_SET"))s->close();s->record();}return S_OK;}).Get(),&token),"WORKER_DENY_HANDLER");self->createPage(0);return S_OK;}).Get());if(FAILED(hr))creationPending--;check(hr,"WORKER_GUARD_CALL");}

 void createPage(int index){if(closing||error!="NONE")return;pages[index].lifetime++;ComPtr<ICoreWebView2Environment3> env3;if(!check(environment.As(&env3),"COMPOSITION_INTERFACE"))return;creationPending++;auto self=shared_from_this();const auto hr=env3->CreateCoreWebView2CompositionController(window,Callback<ICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler>([self,index](HRESULT hr,ICoreWebView2CompositionController*comp)->HRESULT{self->creationPending--;if(self->closing){if(comp){ComPtr<ICoreWebView2Controller> c;comp->QueryInterface(IID_PPV_ARGS(&c));if(c){ComPtr<ICoreWebView2> core;c->get_CoreWebView2(&core);self->identify(core.Get());c->Close();}}return S_OK;}if(!self->check(hr,"CONTROLLER_CREATE")||!comp)return S_OK;auto&p=self->pages[index];p.composition=comp;if(!self->check(comp->QueryInterface(IID_PPV_ARGS(&p.controller)),"CONTROLLER_INTERFACE")||!self->check(p.controller->get_CoreWebView2(&p.core),"CORE"))return S_OK;if(!self->check(p.controller.As(&p.scale),"SCALE")||!self->check(p.composition->put_RootVisualTarget(p.visual.Get()),"VISUAL_TARGET")||!self->check(p.controller->put_IsVisible(TRUE),"VISIBLE"))return S_OK;BOOL actualVisible=FALSE;if(!self->check(p.controller->get_IsVisible(&actualVisible),"VISIBLE_READ")||!actualVisible){self->check(E_FAIL,"VISIBLE_MISMATCH");return S_OK;}if(!self->identify(p.core.Get()))return S_OK;ComPtr<ICoreWebView2_13> core13;ComPtr<ICoreWebView2Profile> profile;LPWSTR name=nullptr;if(!self->check(p.core.As(&core13),"PROFILE_INTERFACE")||!self->check(core13->get_Profile(&profile),"PROFILE")||!self->check(profile->get_ProfileName(&name),"PROFILE_NAME"))return S_OK;p.profile=name?name:L"";if(name)CoTaskMemFree(name);LPWSTR path=nullptr;BOOL privateMode=TRUE;if(!self->check(profile->get_ProfilePath(&path),"PROFILE_PATH")||!self->check(profile->get_IsInPrivateModeEnabled(&privateMode),"PROFILE_MODE"))return S_OK;p.profilePath=path?path:L"";if(path)CoTaskMemFree(path);const auto expected=fs::path(self->udf)/L"EBWebView"/L"Default";HANDLE dir=owned::openDirectory(p.profilePath);p.profileVerified=!privateMode&&owned::plain(dir,expected);if(dir!=INVALID_HANDLE_VALUE)CloseHandle(dir);if(!p.profileVerified){self->check(E_FAIL,"DEFAULT_PROFILE_SCOPE_MISMATCH");return S_OK;}if(index&&!owned::samePath(p.profilePath,self->pages[0].profilePath)){self->check(E_FAIL,"SHARED_PROFILE_MISMATCH");return S_OK;}if(!self->identify(p.core.Get()))return S_OK;self->layout();self->configure(index);return S_OK;}).Get());if(FAILED(hr))creationPending--;check(hr,"CONTROLLER_CALL");}
 void configure(int index){if(error!="NONE")return;auto&p=pages[index];const auto lifetime=p.lifetime;ComPtr<ICoreWebView2Settings> settings;if(!check(p.core->get_Settings(&settings),"SETTINGS")||!settings)return;if(!check(settings->put_AreHostObjectsAllowed(FALSE),"NO_HOST_OBJECTS")||!check(settings->put_IsWebMessageEnabled(FALSE),"NO_WEB_MESSAGE")||!check(settings->put_AreDevToolsEnabled(FALSE),"NO_DEVTOOLS")||!check(settings->put_AreDefaultContextMenusEnabled(FALSE),"NO_CONTEXTMENU")||!check(settings->put_AreDefaultScriptDialogsEnabled(FALSE),"NO_SCRIPT_DIALOGS")||!check(settings->put_IsStatusBarEnabled(FALSE),"NO_STATUSBAR"))return;auto weak=weak_from_this();EventRegistrationToken token{};
  if(!check(p.core->add_NavigationStarting(Callback<ICoreWebView2NavigationStartingEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2NavigationStartingEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;LPWSTR uri=nullptr;a->get_Uri(&uri);const bool allowed=uri&&s->allowed(index,uri);if(allowed&&uri){auto&p=s->pages[index];p.topDocumentPermit.arm(uri,p.scopeGeneration,p.lifetime,s->controls.tasks[demo::owner(index)].epoch);}if(uri)CoTaskMemFree(uri);if(!allowed){s->deniedNavigations++;s->pages[index].navigationBlocked=true;s->check(a->put_Cancel(TRUE),"NAV_CANCEL");return S_OK;}auto&p=s->pages[index];p.document++;p.loaded=false;if(p.navigationRequest){if(!s->check(a->get_NavigationId(&p.navigationId),"NAV_START_ID_READ"))return S_OK;p.navigationDocument=p.document;}s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  // Source is authoritative. Network completion still requires SDK NavigationId.
  if(!check(p.core->add_SourceChanged(Callback<ICoreWebView2SourceChangedEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2SourceChangedEventArgs*a)->HRESULT{if(auto s=weak.lock()){auto&p=s->pages[index];if(!p.core||p.lifetime!=lifetime)return S_OK;BOOL newDocument=TRUE;if(!s->check(a->get_IsNewDocument(&newDocument),"SOURCE_KIND_READ")||!s->refreshSource(index))return S_OK;p.sourceEvents++;if(!newDocument&&p.loaded){if(!p.navigationRequest||!p.navigationInvoked)p.document++;else if(!p.navigationId&&p.navigationAction=="navigate"&&p.url==p.navigationTarget)s->finishSameDocument(index);}s->updateButtons();s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_HistoryChanged(Callback<ICoreWebView2HistoryChangedEventHandler>([weak,index,lifetime](ICoreWebView2*,IUnknown*)->HRESULT{if(auto s=weak.lock()){auto&p=s->pages[index];if(!p.core||p.lifetime!=lifetime)return S_OK;p.historyEvents++;if(!s->refreshSource(index))return S_OK;if(!p.navigationRequest&&p.loaded)p.document++;s->verifyHistoryEntry(index);s->updateButtons();s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_FrameNavigationStarting(Callback<ICoreWebView2NavigationStartingEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2NavigationStartingEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;LPWSTR uri=nullptr;const bool known=SUCCEEDED(a->get_Uri(&uri))&&uri;const auto owner=demo::owner(index);const bool allowed=known&&std::wstring(uri).rfind(L"https://",0)==0&&s->controls.tasks[owner].registered&&s->pages[index].scopeGeneration==s->policy.generations[owner]&&s->policy.allowed(owner,uri,true);if(uri)CoTaskMemFree(uri);if(!allowed){s->deniedFrames++;s->check(a->put_Cancel(TRUE),"FRAME_CANCEL");}s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_NavigationCompleted(Callback<ICoreWebView2NavigationCompletedEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2NavigationCompletedEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;BOOL ok=FALSE;a->get_IsSuccess(&ok);auto&p=s->pages[index];UINT64 navigation=0;if(p.navigationRequest){if(!s->check(a->get_NavigationId(&navigation),"NAV_COMPLETE_ID_READ"))return S_OK;if(navigation!=p.navigationId){s->record();return S_OK;}}p.loaded=ok!=FALSE;LPWSTR actualSource=nullptr;const auto sourceHr=p.core->get_Source(&actualSource);const bool sourceOk=source_state::accept(sourceHr,actualSource,p.url,p.urlKnown);if(actualSource)CoTaskMemFree(actualSource);if(!sourceOk){p.loaded=false;s->check(FAILED(sourceHr)?sourceHr:E_FAIL,"SOURCE_READ_UNKNOWN");}if(p.navigationRequest){const auto id=p.navigationRequest;const bool same=sourceOk&&s->navigationBinding(index)&&navigation==p.navigationId;p.navigationRequest=0;p.navigationAction.clear();const auto url=sourceOk?utf8(p.url):"";COREWEBVIEW2_WEB_ERROR_STATUS e{};a->get_WebErrorStatus(&e);s->result(id,same&&ok!=FALSE&&!p.navigationBlocked,!same?"NAVIGATION_STALE":p.navigationBlocked?"REDIRECT_REJECTED":ok?"NAVIGATED":"NAVIGATION_FAILED","{\"url\":"+json(url)+",\"webError\":"+std::to_string(static_cast<int>(e))+"}");}s->updateButtons();if(ok&&s->error=="NONE")s->status="ready";if(p.createRequest){const auto request=p.createRequest;p.createRequest=0;const auto&task=s->controls.tasks[demo::owner(index)];const bool accepted=sourceOk&&ok!=FALSE&&!s->closing&&task.registered&&!task.paused&&!task.human&&task.epoch==p.createEpoch&&GetTickCount64()<p.createDeadline;p.active=accepted;if(!accepted&&p.controller){p.lifetime++;p.controller->Close();p.core.Reset();p.scale.Reset();p.controller.Reset();p.composition.Reset();p.loaded=false;} s->controls.active[index]=p.active;s->updateButtons();s->result(request,p.active,p.active?"PAGE_CREATED":sourceOk?"PAGE_CREATE_NAVIGATION_FAILED":"SOURCE_READ_UNKNOWN","{\"url\":"+json(sourceOk?utf8(p.url):"")+"}");}s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_DocumentTitleChanged(Callback<ICoreWebView2DocumentTitleChangedEventHandler>([weak,index,lifetime](ICoreWebView2*,IUnknown*)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;LPWSTR title=nullptr;s->pages[index].core->get_DocumentTitle(&title);if(title){s->pages[index].title=std::wstring(title).substr(0,1024);CoTaskMemFree(title);}s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.controller->add_GotFocus(Callback<ICoreWebView2FocusChangedEventHandler>([weak,index,lifetime](ICoreWebView2Controller*,IUnknown*)->HRESULT{if(auto s=weak.lock()){if(s->pages[index].lifetime!=lifetime)return S_OK;if(!s->controls.nativeInput(index,GetForegroundWindow()==s->window))SetFocus(s->window);}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_PermissionRequested(Callback<ICoreWebView2PermissionRequestedEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2PermissionRequestedEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;s->deniedPermissions++;s->check(a->put_State(COREWEBVIEW2_PERMISSION_STATE_DENY),"PERMISSION_DENY");s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  ComPtr<ICoreWebView2_4> c4;if(!check(p.core.As(&c4),"DOWNLOAD_INTERFACE"))return;if(!check(c4->add_DownloadStarting(Callback<ICoreWebView2DownloadStartingEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2DownloadStartingEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;s->deniedDownloads++;s->check(a->put_Cancel(TRUE),"DOWNLOAD_CANCEL");s->check(a->put_Handled(TRUE),"DOWNLOAD_HANDLED");s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  if(!check(p.core->add_NewWindowRequested(Callback<ICoreWebView2NewWindowRequestedEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2NewWindowRequestedEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;s->deniedWindows++;s->check(a->put_Handled(TRUE),"NEWWINDOW_HANDLED");s->record();}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  ComPtr<ICoreWebView2_22> networkCore;if(!check(p.core.As(&networkCore),"RESOURCE_SOURCE_INTERFACE")||!check(networkCore->AddWebResourceRequestedFilterWithRequestSourceKinds(L"*",COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL,COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL),"RESOURCE_FILTER"))return;if(!check(p.core->add_WebResourceRequested(Callback<ICoreWebView2WebResourceRequestedEventHandler>([weak,index,lifetime](ICoreWebView2*,ICoreWebView2WebResourceRequestedEventArgs*a)->HRESULT{if(auto s=weak.lock()){if(!s->pages[index].core||s->pages[index].lifetime!=lifetime)return S_OK;ComPtr<ICoreWebView2WebResourceRequest> req;a->get_Request(&req);LPWSTR uri=nullptr;if(req)req->get_Uri(&uri);ComPtr<ICoreWebView2WebResourceRequestedEventArgs2> sourceArgs;COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS kind=COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE;const bool known=SUCCEEDED(a->QueryInterface(IID_PPV_ARGS(&sourceArgs)))&&SUCCEEDED(sourceArgs->get_RequestedSourceKind(&kind));const bool document=known&&kind==COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT;if(!document)s->deniedWorkerResources++;COREWEBVIEW2_WEB_RESOURCE_CONTEXT context=COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER;const bool contextKnown=SUCCEEDED(a->get_ResourceContext(&context));LPWSTR method=nullptr;const bool methodKnown=req&&SUCCEEDED(req->get_Method(&method))&&method;
const bool eligible=methodKnown&&resource_policy::eligible(known,kind,contextKnown,context,method?method:L"");
const auto owner=demo::owner(index);const bool fixtureRequest=uri&&std::wstring(uri).rfind(s->policy.fixture+L"/",0)==0;const auto&sourcePage=s->pages[index];const auto&resourceDocument=sourcePage.navigationRequest?sourcePage.navigationTarget:sourcePage.url;const bool fixtureDocument=resourceDocument.rfind(s->policy.fixture+L"/",0)==0;
const bool documentPermit=context!=COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT||!fixtureRequest||uri&&s->pages[index].topDocumentPermit.consume(uri,sourcePage.scopeGeneration,sourcePage.lifetime,s->controls.tasks[owner].epoch);const bool allowed=eligible&&uri&&documentPermit&&(!fixtureRequest||fixtureDocument)&&sourcePage.scopeGeneration==s->policy.generations[owner]&&(resource_policy::nonNetworkStatic(uri,context,sourcePage.url)&&(s->policy.publicMode[owner]||!s->policy.scopes[owner].empty())||s->policy.allowed(owner,uri,resource_policy::publicChild(context)));if(method)CoTaskMemFree(method);if(uri)CoTaskMemFree(uri);if(!allowed){s->deniedResources++;s->record();ComPtr<ICoreWebView2WebResourceResponse> response;if(!s->check(s->environment->CreateWebResourceResponse(nullptr,403,L"Blocked",L"Content-Type: text/plain",&response),"BLOCK_RESPONSE_CREATE")||!s->check(a->put_Response(response.Get()),"BLOCK_RESPONSE_SET"))s->close();}}return S_OK;}).Get(),&token),"HANDLER_REGISTER"))return;
  check(p.core->Navigate(p.url.c_str()),"NAVIGATE");
 }
 bool captureValid(const Capture&c)const{const auto&p=pages[c.page];return !closing&&c.active&&p.loaded&&p.controller.Get()==c.controller&&p.document==c.document&&p.geometry==c.geometry&&p.sequence==c.sequence&&controls.tasks[demo::owner(c.page)].epoch==c.epoch&&!controls.tasks[demo::owner(c.page)].paused&&!controls.tasks[demo::owner(c.page)].human&&presentation==c.presentation&&GetTickCount64()<c.deadline;}
 void capture(int page,unsigned request){if(closing||error!="NONE"||page<0||page>7){if(request)result(request,false,"HOST_FAILED");return;}auto&p=pages[page];if(pending||captureUncertain||p.scriptPending||!p.loaded||controls.tasks[demo::owner(page)].paused||controls.tasks[demo::owner(page)].human){if(request)result(request,false,"CAPTURE_UNAVAILABLE");return;}auto a=std::make_shared<Capture>();a->page=page;a->request=request;a->document=p.document;a->geometry=p.geometry;a->epoch=controls.tasks[demo::owner(page)].epoch;a->sequence=++p.sequence;a->controller=p.controller.Get();a->presentation=presentation;a->deadline=GetTickCount64()+15000;a->minimized=IsIconic(window)!=FALSE;a->baseline=snapshot();a->stream.Attach(new LimitedStream());pending=a;if(!SetTimer(window,captureTimer,20,nullptr)){pending.reset();a->active=false;if(request)result(request,false,"CAPTURE_TIMER_FAILED");check(E_FAIL,"CAPTURE_TIMER_FAILED");return;}record();auto weak=weak_from_this();
  const auto hr=p.core->CapturePreview(COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG,a->stream.Get(),Callback<ICoreWebView2CapturePreviewCompletedHandler>([weak,a](HRESULT hr)->HRESULT{if(auto s=weak.lock()){if(s->pending==a)s->pending.reset();KillTimer(s->window,captureTimer);if(!s->captureValid(*a)||FAILED(hr)){a->active=false;if(a->request)s->result(a->request,false,FAILED(hr)?"CAPTURE_COMPLETION":"CAPTURE_STALE");s->updateButtons();s->record();return S_OK;}if(a->minimized&&std::string(min_window::reject(a->baseline,s->snapshot()))!="NONE"){a->active=false;if(a->request)s->result(a->request,false,"CAPTURE_OWN_WINDOW_CHANGED");s->record();return S_OK;}const auto bytes=a->stream->snapshot();if(!s->validPng(bytes)){a->active=false;if(a->request)s->result(a->request,false,"PNG_INVALID");s->record();return S_OK;}if(!s->captureValid(*a)){a->active=false;if(a->request)s->result(a->request,false,"CAPTURE_STALE");s->record();return S_OK;}const std::wstring leaf=L"page-"+std::to_wstring(a->page)+L"-"+std::to_wstring(a->sequence)+L".png";HANDLE file=s->directories->createNew(leaf.c_str());DWORD count=0;const bool saved=file!=INVALID_HANDLE_VALUE&&WriteFile(file,bytes.data(),static_cast<DWORD>(bytes.size()),&count,nullptr)&&count==bytes.size();if(file!=INVALID_HANDLE_VALUE)CloseHandle(file);a->active=false;if(!saved){if(a->request)s->result(a->request,false,"PNG_SAVE_FAILED");s->record();return S_OK;}auto&p=s->pages[a->page];p.lastPng=utf8(leaf);p.thumbnail=bytes;if(a->request)s->result(a->request,true,"CAPTURED","{\"file\":"+json(p.lastPng)+",\"width\":"+std::to_string(s->pngNumber(bytes,16))+",\"height\":"+std::to_string(s->pngNumber(bytes,20))+",\"bytes\":"+std::to_string(bytes.size())+",\"controllerIdentity\":"+std::to_string(reinterpret_cast<std::uintptr_t>(p.controller.Get()))+",\"document\":"+std::to_string(p.document)+",\"geometry\":"+std::to_string(p.geometry)+",\"readOnly\":true}");s->updateButtons();s->record();}return S_OK;}).Get());if(FAILED(hr)){pending.reset();a->active=false;KillTimer(window,captureTimer);if(request)result(request,false,"CAPTURE_CALL");record();}}
 static unsigned pngNumber(const std::vector<unsigned char>&b,size_t i){return(unsigned(b[i])<<24)|(unsigned(b[i+1])<<16)|(unsigned(b[i+2])<<8)|b[i+3];}
 bool validPng(const std::vector<unsigned char>&b){if(b.size()<24||b.size()>8000000||memcmp(b.data(),"\x89PNG\r\n\x1a\n",8)||memcmp(b.data()+12,"IHDR",4))return false;const auto w=pngNumber(b,16),h=pngNumber(b,20);if(!w||!h||w>8192||h>16384||uint64_t(w)*h>32000000||w!=static_cast<unsigned>(bounds.right-bounds.left)||h!=static_cast<unsigned>(bounds.bottom-bounds.top))return false;ComPtr<IStream> input;input.Attach(SHCreateMemStream(b.data(),static_cast<UINT>(b.size())));ComPtr<IWICImagingFactory> factory;ComPtr<IWICBitmapDecoder> decoder;ComPtr<IWICBitmapFrameDecode> frame;return input&&SUCCEEDED(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&factory)))&&SUCCEEDED(factory->CreateDecoderFromStream(input.Get(),nullptr,WICDecodeMetadataCacheOnLoad,&decoder))&&SUCCEEDED(decoder->GetFrame(0,&frame));}
 void tickCapture(){if(!pending||GetTickCount64()<pending->deadline)return;auto a=pending;a->active=false;captureUncertain=true;KillTimer(window,captureTimer);if(a->request)result(a->request,false,"CAPTURE_TIMEOUT_UNKNOWN");record();}
 bool inputCommitValid(int page)const{const auto&p=pages[page];const auto&t=controls.tasks[demo::owner(page)];return !closing&&p.active&&p.core&&p.controller.Get()==p.inputIdentity&&p.lifetime==p.inputLifetime&&p.document==p.inputDocument&&t.registered&&!t.paused&&!t.human&&t.epoch==p.inputEpoch&&GetTickCount64()<p.inputDeadline;}
 void finishInput(Command c){auto&p=pages[c.target];if(!p.inputOperation){result(c.id,false,"INPUT_LEASE_MISSING");return;}if(!p.core||p.controller.Get()!=p.inputIdentity||p.lifetime!=p.inputLifetime||GetTickCount64()>=c.deadline){result(c.id,false,"INPUT_RELEASE_UNKNOWN");return;}std::string method,params;bool mouse=false;unsigned key=0;if(p.mouseHeld){mouse=true;method="Input.dispatchMouseEvent";params="{\"type\":\"mouseReleased\",\"x\":0,\"y\":0,\"button\":\"left\",\"clickCount\":1}";}else if(!p.keysHeld.empty()){key=p.keysHeld.back();method="Input.dispatchKeyEvent";params="{\"type\":\"keyUp\",\"windowsVirtualKeyCode\":"+std::to_string(key)+",\"nativeVirtualKeyCode\":"+std::to_string(key)+"}";}else{const bool commit=inputCommitValid(c.target);p.inputOperation=false;updateButtons();record();result(c.id,commit,commit?"INPUT_COMMITTED":"INPUT_COMMIT_STALE","{\"released\":true,\"commitAllowed\":"+std::string(commit?"true":"false")+"}");return;}p.scriptPending=true;const auto lifetime=p.lifetime;const auto controller=p.controller.Get();auto weak=weak_from_this();const auto hr=p.core->CallDevToolsProtocolMethod(wide(method).c_str(),wide(params).c_str(),Callback<ICoreWebView2CallDevToolsProtocolMethodCompletedHandler>([weak,c,lifetime,controller,mouse,key](HRESULT hr,LPCWSTR)->HRESULT{if(auto self=weak.lock()){auto&p=self->pages[c.target];p.scriptPending=false;if(FAILED(hr)||p.lifetime!=lifetime||p.controller.Get()!=controller||GetTickCount64()>=c.deadline){self->result(c.id,false,"INPUT_RELEASE_UNKNOWN");return S_OK;}if(mouse)p.mouseHeld=false;else p.keysHeld.erase(std::remove(p.keysHeld.begin(),p.keysHeld.end(),key),p.keysHeld.end());self->finishInput(c);}return S_OK;}).Get());if(FAILED(hr)){p.scriptPending=false;result(c.id,false,"INPUT_RELEASE_UNKNOWN");}}
 // Fixed internal CDP allowlist, never forwarded from Agent CLI/MCP.
 void protocol(Command c){auto&p=pages[c.target];if(p.scriptPending||!p.loaded||(pending&&pending->page==c.target)){result(c.id,false,"PAGE_BUSY");return;}const auto split=c.value.find('\n');if(split==std::string::npos){result(c.id,false,"PROTOCOL_SCOPE");return;}const auto method=c.value.substr(0,split);if(method!="DOM.describeNode"&&method!="DOM.getNodeForLocation"&&method!="Page.getFrameTree"&&method!="Page.createIsolatedWorld"&&method!="Runtime.evaluate"&&method!="Input.dispatchMouseEvent"&&method!="Input.dispatchKeyEvent"&&method!="Input.insertText"){result(c.id,false,"PROTOCOL_SCOPE");return;}const auto params=wide(c.value.substr(split+1));if(params.empty()){result(c.id,false,"PROTOCOL_ENCODING");return;}if(method.rfind("Input.",0)==0){const auto&t=controls.tasks[c.caller];if(!p.inputOperation||p.inputEpoch!=t.epoch||p.inputDocument!=p.document||p.inputLifetime!=p.lifetime||p.inputIdentity!=p.controller.Get()){result(c.id,false,"INPUT_LEASE_STALE");return;}if(method=="Input.dispatchMouseEvent"){if(c.value.find("mousePressed")!=std::string::npos)p.mouseHeld=true;}if(method=="Input.dispatchKeyEvent"){const auto field=c.value.find("windowsVirtualKeyCode\":");if(field==std::string::npos){result(c.id,false,"UNSUPPORTED_KEY");return;}const auto code=static_cast<unsigned>(std::stoul(c.value.substr(field+23)));if(c.value.find("rawKeyDown")!=std::string::npos)p.keysHeld.push_back(code);}}
 p.scriptPending=true;const auto epoch=controls.tasks[demo::owner(c.target)].epoch,doc=p.document;const auto controller=p.controller.Get();auto weak=weak_from_this();const auto hr=p.core->CallDevToolsProtocolMethod(wide(method).c_str(),params.c_str(),Callback<ICoreWebView2CallDevToolsProtocolMethodCompletedHandler>([weak,c,epoch,doc,controller,method](HRESULT hr,LPCWSTR data)->HRESULT{if(auto s=weak.lock()){auto&p=s->pages[c.target];p.scriptPending=false;if(SUCCEEDED(hr)&&c.operation=="cdp"){if(method=="Input.dispatchMouseEvent"&&c.value.find("mouseReleased")!=std::string::npos)p.mouseHeld=false;if(method=="Input.dispatchKeyEvent"&&c.value.find("keyUp")!=std::string::npos){const auto field=c.value.find("windowsVirtualKeyCode\":");if(field!=std::string::npos){const auto code=static_cast<unsigned>(std::stoul(c.value.substr(field+23)));p.keysHeld.erase(std::remove(p.keysHeld.begin(),p.keysHeld.end(),code),p.keysHeld.end());}}}const bool same=!s->closing&&p.document==doc&&p.controller.Get()==controller&&s->controls.tasks[demo::owner(c.target)].registered&&s->controls.tasks[demo::owner(c.target)].epoch==epoch&&!s->controls.tasks[demo::owner(c.target)].paused&&!s->controls.tasks[demo::owner(c.target)].human&&GetTickCount64()<c.deadline;const auto value=data?utf8(data):"null";s->result(c.id,same&&SUCCEEDED(hr)&&value.size()<=60000,!same?"SCRIPT_STALE":FAILED(hr)?"PROTOCOL_FAILED":value.size()>60000?"OUTPUT_LIMIT":"OK",value.size()<=60000?value:"null");s->updateButtons();s->record();}return S_OK;}).Get());if(FAILED(hr)){p.scriptPending=false;result(c.id,false,"PROTOCOL_CALL");}}
 void toolScript(Command c){auto&p=pages[c.target];if(p.scriptPending||!p.loaded||(pending&&pending->page==c.target)){result(c.id,false,"PAGE_BUSY");return;}const auto expression=wide(c.value);if(expression.empty()){result(c.id,false,"SCRIPT_ENCODING");return;}p.scriptPending=true;const auto epoch=controls.tasks[demo::owner(c.target)].epoch,doc=p.document;const auto controller=p.controller.Get();auto weak=weak_from_this();const auto hr=p.core->ExecuteScript(expression.c_str(),Callback<ICoreWebView2ExecuteScriptCompletedHandler>([weak,c,epoch,doc,controller](HRESULT hr,LPCWSTR data)->HRESULT{if(auto s=weak.lock()){auto&p=s->pages[c.target];p.scriptPending=false;if(SUCCEEDED(hr)&&c.operation=="cdp"){if(c.value.find("Input.dispatchMouseEvent")!=std::string::npos&&c.value.find("mouseReleased")!=std::string::npos)p.mouseHeld=false;if(c.value.find("Input.dispatchKeyEvent")!=std::string::npos&&c.value.find("keyUp")!=std::string::npos){const auto field=c.value.find("windowsVirtualKeyCode\":");if(field!=std::string::npos){const auto code=static_cast<unsigned>(std::stoul(c.value.substr(field+23)));p.keysHeld.erase(std::remove(p.keysHeld.begin(),p.keysHeld.end(),code),p.keysHeld.end());}}}const bool same=!s->closing&&p.document==doc&&p.controller.Get()==controller&&s->controls.tasks[demo::owner(c.target)].epoch==epoch&&!s->controls.tasks[demo::owner(c.target)].paused&&!s->controls.tasks[demo::owner(c.target)].human;const auto text=data?utf8(data):"null";s->result(c.id,same&&SUCCEEDED(hr)&&text.size()<=60000,!same?"SCRIPT_STALE":FAILED(hr)?"SCRIPT_FAILED":text.size()>60000?"OUTPUT_LIMIT":"OK",text.size()<=60000?text:"null");s->updateButtons();s->record();}return S_OK;}).Get());if(FAILED(hr)){p.scriptPending=false;result(c.id,false,"SCRIPT_CALL");}}
 void script(Command c,bool mutation){auto&p=pages[c.target];if(p.scriptPending||!p.loaded||(pending&&pending->page==c.target)){result(c.id,false,"PAGE_BUSY");return;}p.scriptPending=true;const auto epoch=controls.tasks[demo::owner(c.target)].epoch,doc=p.document;const auto controller=p.controller.Get();std::wstring expression;
  if(mutation){const std::wstring v(c.value.begin(),c.value.end());expression=L"(()=>{const v='"+v+L"';document.querySelector('#saved').value=v;document.querySelector('#marker').textContent=v;document.querySelector('#zone').style.background='"+(c.target==0?std::wstring(L"#8ac4a1"):std::wstring(L"#9cb7da"))+L"';window.__demoRevision=(window.__demoRevision||0)+1;document.querySelector('#zone').style.background=(window.__demoRevision%2)?'#8ac4a1':'#b29bd6';scrollTo(0,420);if(!location.hash)history.pushState({demo:true},'', '#owned');return {revision:window.__demoRevision,formLength:document.querySelector('#saved').value.length,scrollY,historyLength:history.length,marker:document.querySelector('#marker').textContent}})()";}
  else expression=LR"JS((()=>({revision:window.__demoRevision||0,formLength:document.querySelector('#saved').value.length,scrollY,historyLength:history.length,marker:document.querySelector('#marker').textContent}))())JS";
  auto weak=weak_from_this();const auto hr=p.core->ExecuteScript(expression.c_str(),Callback<ICoreWebView2ExecuteScriptCompletedHandler>([weak,c,epoch,doc,controller](HRESULT hr,LPCWSTR data)->HRESULT{if(auto s=weak.lock()){auto&p=s->pages[c.target];p.scriptPending=false;if(SUCCEEDED(hr)&&c.operation=="cdp"){if(c.value.find("Input.dispatchMouseEvent")!=std::string::npos&&c.value.find("mouseReleased")!=std::string::npos)p.mouseHeld=false;if(c.value.find("Input.dispatchKeyEvent")!=std::string::npos&&c.value.find("keyUp")!=std::string::npos){const auto field=c.value.find("windowsVirtualKeyCode\":");if(field!=std::string::npos){const auto code=static_cast<unsigned>(std::stoul(c.value.substr(field+23)));p.keysHeld.erase(std::remove(p.keysHeld.begin(),p.keysHeld.end(),code),p.keysHeld.end());}}}const bool same=p.controller.Get()==controller&&p.document==doc&&s->controls.tasks[demo::owner(c.target)].epoch==epoch&&!s->closing;if(!same||FAILED(hr)||!data){s->result(c.id,false,same?"SCRIPT_FAILED":"SCRIPT_STALE");}else {const auto text=utf8(data);if(text.size()>2048)s->result(c.id,false,"SCRIPT_OUTPUT_LIMIT");else{p.lastStats=text;s->result(c.id,true,"OK",text);}}s->updateButtons();s->record();}return S_OK;}).Get());if(FAILED(hr)){p.scriptPending=false;result(c.id,false,"SCRIPT_CALL");record();}}
 void command(Command c){requestDeadlines[c.id]=c.deadline?c.deadline:GetTickCount64()+8000;eventDeadline=requestDeadlines[c.id];if(GetTickCount64()>=eventDeadline){result(c.id,false,"REQUEST_DEADLINE_UNKNOWN");eventDeadline=0;return;}if(c.operation=="close"){result(c.id,true,"CLOSE_REQUESTED");close();return;}if(closing){result(c.id,false,"CLOSING");return;}if(error!="NONE"){result(c.id,false,"HOST_FAILED");return;}if(c.operation=="client-lost"){if(c.caller!=demo::owner(c.target)){result(c.id,false,"OWNER_MISMATCH");return;}auto&t=controls.tasks[demo::owner(c.target)];t.paused=true;t.epoch++;result(c.id,true,"CLIENT_LOST_PAUSED");record();return;}if(c.operation=="label"){const auto cut=c.value.find('\n');pages[c.target].agentLabel=wide(c.value.substr(0,cut));pages[c.target].taskLabel=cut==std::string::npos?L"":wide(c.value.substr(cut+1));result(c.id,true,"LABELLED");record();return;}if(c.operation=="unregister"){policy.scopes[c.caller].clear();policy.publicMode[c.caller]=false;policy.generations[c.caller]++;auto&t=controls.tasks[demo::owner(c.target)];t.registered=false;t.paused=true;t.human=false;t.epoch++;pages[c.target].thumbnail.clear();result(c.id,true,"ENDED");record();return;}if(c.operation=="scope-check"){std::vector<std::wstring> origins;bool publicMode=false;if(!policy.parseScope(wide(c.value),origins,publicMode)){result(c.id,false,"INVALID_ORIGIN_NATIVE");return;}for(const auto&value:origins)if(!policy.publicOrigin(value)){result(c.id,false,"DNS_NONPUBLIC");return;}result(c.id,true,"SCOPE_VALIDATED");return;}if(c.operation=="register"){if(c.caller!=demo::owner(c.target)){result(c.id,false,"OWNER_MISMATCH");return;}std::vector<std::wstring> origins;bool publicMode=false;if(!policy.parseScope(wide(c.value),origins,publicMode)){result(c.id,false,"INVALID_ORIGIN_NATIVE");return;}policy.scopes[c.caller]=origins;policy.publicMode[c.caller]=publicMode;policy.generations[c.caller]++;controls.tasks[demo::owner(c.target)].paused=false;controls.tasks[demo::owner(c.target)].human=false;controls.tasks[demo::owner(c.target)].epoch++;if(c.caller!=demo::owner(c.target)){result(c.id,false,"OWNER_MISMATCH");return;}controls.tasks[demo::owner(c.target)].registered=true;result(c.id,true,"REGISTERED");record();return;}
  if(c.operation=="view"||c.operation=="overview"||c.operation=="request-takeover"||c.operation=="confirm"||c.operation=="cancel"||c.operation=="request-handback"||c.operation=="minimize"||c.operation=="restore"||c.operation=="human-back"||c.operation=="human-forward"||c.operation=="human-reload"){
   // Supervisor-only wire operations. Broker never forwards these from Agent channels.
   if(c.operation=="human-back")ui(backId);else if(c.operation=="human-forward")ui(forwardId);else if(c.operation=="human-reload")ui(reloadId);else if(c.operation=="view")ui(pageBaseId+c.target);else if(c.operation=="overview")ui(overviewId);else if(c.operation=="request-takeover")ui(takeoverId);else if(c.operation=="confirm")ui(confirmId);else if(c.operation=="cancel")ui(cancelId);else if(c.operation=="request-handback")ui(returnId);else if(c.operation=="minimize")ShowWindow(window,SW_MINIMIZE);else ShowWindow(window,SW_RESTORE);result(c.id,true,"SUPERVISOR_DELIVERED");record();return;
  }
  if(c.operation=="input-expire-test"){pages[c.target].inputDeadline=GetTickCount64();result(c.id,true,"TEST_DEADLINE_EXPIRED");return;}if(c.operation=="input-end"){if(c.caller!=demo::owner(c.target)){result(c.id,false,"OWNER_MISMATCH");return;}finishInput(c);return;}
  const auto code=controls.authorize(c.caller,c.target);if(std::string(code)!="NONE"){result(c.id,false,code);return;}if(c.operation=="page-new"){auto&p=pages[c.target];p.scopeGeneration=policy.generations[c.caller];if(p.active||p.createRequest){result(c.id,false,"PAGE_CAPACITY");return;}if(p.core){LPWSTR current=nullptr;const auto hr=p.core->get_Source(&current);const bool known=source_state::accept(hr,current,p.url,p.urlKnown);if(current)CoTaskMemFree(current);if(!known){result(c.id,false,"SOURCE_READ_UNKNOWN");check(E_FAIL,"SOURCE_READ_UNKNOWN");return;}p.active=true;controls.active[c.target]=true;result(c.id,true,"PAGE_CREATED","{\"url\":"+json(utf8(p.url))+"}");updateButtons();record();}else{p.url=origin+(c.caller?L"/agent-b":L"/agent-a");p.urlKnown=false;p.title.clear();p.thumbnail.clear();p.lastPng.clear();p.inputOperation=false;p.mouseHeld=false;p.keysHeld.clear();p.createRequest=c.id;p.createEpoch=controls.tasks[c.caller].epoch;p.createDeadline=c.deadline;createPage(c.target);}return;}if(c.operation=="page-close"){closePage(c.target,c.id);return;}if(c.operation=="input-begin"){if(ownerBusy(c.caller)){result(c.id,false,"PAGE_BUSY");return;}pages[c.target].inputOperation=true;pages[c.target].inputEpoch=controls.tasks[c.caller].epoch;pages[c.target].inputDocument=pages[c.target].document;pages[c.target].inputLifetime=pages[c.target].lifetime;pages[c.target].inputDeadline=c.deadline;pages[c.target].inputIdentity=pages[c.target].controller.Get();result(c.id,true,"INPUT_STARTED");updateButtons();return;}if(!pages[c.target].active){result(c.id,false,"PAGE_NOT_ACTIVE");return;}if(c.operation=="history"){beginHistory(c.target,c.id,c.value,c.deadline);return;}if(c.operation=="navigate"){auto&p=pages[c.target];const auto url=wide(c.value);if(!allowed(c.target,url)){result(c.id,false,"URL_REJECTED");return;}if(p.scriptPending||p.navigationRequest||pending){result(c.id,false,"PAGE_BUSY");return;}p.navigationId=0;p.navigationRequest=c.id;p.navigationEpoch=controls.tasks[demo::owner(c.target)].epoch;p.navigationController=p.controller.Get();p.navigationDeadline=c.deadline;p.navigationBlocked=false;p.navigationHuman=false;p.navigationLifetime=p.lifetime;p.navigationGeneration=p.scopeGeneration;p.navigationAction="navigate";p.navigationTarget=url;p.navigationEntry=0;p.navigationVerifying=false;p.navigationInvoked=true;p.document++;p.navigationDocument=p.document;const auto hr=p.core->Navigate(url.c_str());if(FAILED(hr)){p.navigationRequest=0;result(c.id,false,"NAVIGATE_CALL");}record();}else if(c.operation=="cdp")protocol(c);else if(c.operation=="script")toolScript(c);else if(c.operation=="capture")capture(c.target,c.id);else script(c,c.operation=="mutate");}
 void resetInputCapture(bool release=true){if(release&&GetCapture()==window)ReleaseCapture();mouseCaptured=false;inputPage=-1;inputEpoch=0;inputDocument=0;inputController=nullptr;}
 bool mouse(UINT message,WPARAM w,LPARAM l){
  POINT point{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(message==WM_MOUSEWHEEL||message==WM_MOUSEHWHEEL)ScreenToClient(window,&point);
  if(mouseCaptured&&GetCapture()!=window)resetInputCapture(false);if(!ui::insideRounded(bounds,point,ui::px(ui::containerRadius,dpi))&&!mouseCaptured)return false;
  const int selected=controls.selected;auto&page=pages[selected];const auto release=[&]{resetInputCapture();};
  if(!controls.nativeInput(selected,GetForegroundWindow()==window)||closing||error!="NONE"||IsIconic(window)||!page.loaded||!page.composition){release();return true;}
  if(mouseCaptured&&(inputPage!=selected||inputEpoch!=controls.tasks[demo::owner(selected)].epoch||inputDocument!=page.document||inputController!=page.controller.Get())){release();return true;}
  if(message==WM_LBUTTONDOWN){const auto epoch=controls.tasks[demo::owner(selected)].epoch,document=page.document;const auto controller=page.controller.Get();
   if(FAILED(page.controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC))||!controls.nativeInput(selected,GetForegroundWindow()==window)||selected!=controls.selected||controls.tasks[demo::owner(selected)].epoch!=epoch||page.document!=document||page.controller.Get()!=controller){release();return true;}
   inputPage=selected;inputEpoch=epoch;inputDocument=document;inputController=controller;SetCapture(window);if(GetCapture()!=window){release();record();return true;}mouseCaptured=true;
  }
  GUITHREADINFO focus{};focus.cbSize=sizeof(focus);if(!GetGUIThreadInfo(GetCurrentThreadId(),&focus)||!focus.hwndFocus||(focus.hwndFocus!=window&&!IsChild(window,focus.hwndFocus))){release();return true;}
  DWORD data=message==WM_MOUSEWHEEL||message==WM_MOUSEHWHEEL?static_cast<DWORD>(GET_WHEEL_DELTA_WPARAM(w)):0;point.x-=bounds.left;point.y-=bounds.top;
  if(!controls.nativeInput(selected,GetForegroundWindow()==window)){release();return true;}
  const auto sent=page.composition->SendMouseInput(static_cast<COREWEBVIEW2_MOUSE_EVENT_KIND>(message),static_cast<COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS>(GET_KEYSTATE_WPARAM(w)),data,point);if(FAILED(sent)){release();check(sent,"INPUT_SEND_FAILED");return true;}if(message==WM_LBUTTONUP)release();return true;
 }
 void close(){if(closing)return;closing=true;stopFeedback();for(auto&t:controls.tasks){t.paused=true;t.epoch++;}if(pending)pending->active=false;KillTimer(window,captureTimer);for(auto&p:pages)if(p.controller)check(p.controller->Close(),"CONTROLLER_CLOSE");if(workerGuardController)check(workerGuardController->Close(),"WORKER_GUARD_CLOSE");closeDeadline=GetTickCount64()+8000;status="closing";if(!SetTimer(window,closeTimer,30,nullptr)){error="CLOSE_TIMER_FAILED";status="close-unknown";record();DestroyWindow(window);return;}record();}
 void tickClose(){bool drained=creationPending==0&&historyQueries==0&&!pending;for(const auto&p:pages)drained=drained&&!p.scriptPending;if(drained&&!released){for(auto&p:pages){p.core.Reset();p.scale.Reset();p.controller.Reset();p.composition.Reset();}workerGuardCore.Reset();workerGuardController.Reset();environment.Reset();released=true;}bool retiredExited=true;for(const auto&r:retiredBrowsers)retiredExited=retiredExited&&WaitForSingleObject(r.handle,0)==WAIT_OBJECT_0;if(drained&&retiredExited&&((browser&&WaitForSingleObject(browser,0)==WAIT_OBJECT_0)||!environmentInvoked)){status="closed-own-browser-observed";record();KillTimer(window,closeTimer);DestroyWindow(window);return;}if(GetTickCount64()>=closeDeadline){status="close-unknown";error="CLOSE_DEADLINE";record();KillTimer(window,closeTimer);DestroyWindow(window);}}
};
std::shared_ptr<Host> host;

// Shared drawing consumes named C tokens. Real BUTTON HWNDs keep accessibility,
// keyboard, focus, disabled state and the original trusted WM_COMMAND route.
void text(HDC dc,const std::wstring&v,RECT r,COLORREF color,HFONT font){SetTextColor(dc,color);SetBkMode(dc,TRANSPARENT);SelectObject(dc,font);DrawTextW(dc,v.c_str(),static_cast<int>(v.size()),&r,DT_LEFT|DT_SINGLELINE|DT_VCENTER|DT_END_ELLIPSIS|DT_NOPREFIX);}
void surface(HDC dc,RECT r,COLORREF fill,COLORREF edge,int radius,int width=1){const auto b=CreateSolidBrush(fill);const auto p=CreatePen(PS_SOLID,width,edge);const auto ob=SelectObject(dc,b),op=SelectObject(dc,p);RoundRect(dc,r.left,r.top,r.right,r.bottom,radius*2,radius*2);SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(b);DeleteObject(p);}
void drawThumbnail(HDC dc,const std::vector<unsigned char>&b,const RECT&r,int roundDip=ui::controlRadius){if(b.empty())return;ComPtr<IStream> stream;stream.Attach(SHCreateMemStream(b.data(),static_cast<UINT>(b.size())));ComPtr<IWICImagingFactory> factory;ComPtr<IWICBitmapDecoder> decoder;ComPtr<IWICBitmapFrameDecode> frame;ComPtr<IWICFormatConverter> pixels;if(FAILED(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&factory)))||FAILED(factory->CreateDecoderFromStream(stream.Get(),nullptr,WICDecodeMetadataCacheOnLoad,&decoder))||FAILED(decoder->GetFrame(0,&frame))||FAILED(factory->CreateFormatConverter(&pixels))||FAILED(pixels->Initialize(frame.Get(),GUID_WICPixelFormat32bppBGRA,WICBitmapDitherTypeNone,nullptr,0,WICBitmapPaletteTypeCustom)))return;UINT w=0,h=0;frame->GetSize(&w,&h);if(!w||!h||uint64_t(w)*h>32000000)return;std::vector<unsigned char> bitmap(static_cast<size_t>(w)*h*4);if(FAILED(pixels->CopyPixels(nullptr,w*4,static_cast<UINT>(bitmap.size()),bitmap.data())))return;BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=static_cast<LONG>(w);info.bmiHeader.biHeight=-static_cast<LONG>(h);info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;SetStretchBltMode(dc,HALFTONE);const double fit=std::min(double(r.right-r.left)/w,double(r.bottom-r.top)/h);const int dw=static_cast<int>(w*fit),dh=static_cast<int>(h*fit);const int drawX=r.left+((r.right-r.left)-dw)/2,drawY=r.top+((r.bottom-r.top)-dh)/2;const int saved=SaveDC(dc);const auto mask=CreateRoundRectRgn(drawX,drawY,drawX+dw+1,drawY+dh+1,ui::px(roundDip*2,host->dpi),ui::px(roundDip*2,host->dpi));ExtSelectClipRgn(dc,mask,RGN_AND);StretchDIBits(dc,drawX,drawY,dw,dh,0,0,w,h,bitmap.data(),&info,DIB_RGB_COLORS,SRCCOPY);RestoreDC(dc,saved);DeleteObject(mask);}

LRESULT CALLBACK buttonProc(HWND window,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_MOUSEMOVE){if(!GetPropW(window,L"hover")){SetPropW(window,L"hover",reinterpret_cast<HANDLE>(1));TRACKMOUSEEVENT t{sizeof(t),TME_LEAVE,window,0};TrackMouseEvent(&t);InvalidateRect(window,nullptr,FALSE);}}else if(m==WM_MOUSELEAVE){RemovePropW(window,L"hover");InvalidateRect(window,nullptr,FALSE);}else if(m==WM_NCDESTROY){RemovePropW(window,L"hover");RemoveWindowSubclass(window,buttonProc,1);}return DefSubclassProc(window,m,w,l);}
LRESULT CALLBACK addressProc(HWND window,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_CHAR&&w==VK_RETURN)return 0;if(m==WM_KEYDOWN&&w==VK_RETURN)return 0;if(m==WM_NCDESTROY)RemoveWindowSubclass(window,addressProc,2);return DefSubclassProc(window,m,w,l);}
void paintButton(const DRAWITEMSTRUCT&d){if(!IsWindowVisible(d.hwndItem))return;const auto dpi=host->dpi;const int pad=ui::px(8,dpi),id=static_cast<int>(d.CtlID);RECT r=d.rcItem;const bool disabled=(d.itemState&ODS_DISABLED)!=0,focused=(d.itemState&ODS_FOCUS)!=0,over=GetPropW(d.hwndItem,L"hover")!=nullptr;
 const auto back=CreateSolidBrush(id==overviewId||id>=pageBaseId?ui::bg:ui::panel);FillRect(d.hDC,&r,back);DeleteObject(back);
 if(id>=pageBaseId&&id<pageBaseId+8){const int n=id-pageBaseId;const auto&p=host->pages[n];const auto&t=host->controls.tasks[demo::owner(n)];const bool selected=host->controls.selected==n,asking=host->controls.pending!=demo::Pending::none&&demo::owner(host->controls.selected)==demo::owner(n);const auto fill=host->feedback(d.hwndItem,selected?ui::selected:over?ui::hover:ui::panel,selected?140:120);surface(d.hDC,r,fill,fill,ui::px(6,dpi));if(selected){RECT stripe{ui::px(4,dpi),ui::px(8,dpi),ui::px(7,dpi),r.bottom-ui::px(8,dpi)};surface(d.hDC,stripe,ui::accent,ui::accent,ui::px(1,dpi));}
  RECT thumb{pad,(r.bottom-ui::px(36,dpi))/2,pad+ui::px(52,dpi),(r.bottom+ui::px(36,dpi))/2};surface(d.hDC,thumb,ui::preview,ui::preview,ui::px(4,dpi));if(!p.thumbnail.empty())drawThumbnail(d.hDC,p.thumbnail,thumb);else text(d.hDC,L"预览",thumb,ui::muted,host->smallFont);const int x=thumb.right+ui::px(9,dpi);const COLORREF dot=asking?ui::pending:t.human?ui::human:ui::muted;const auto b=CreateSolidBrush(dot);const auto old=SelectObject(d.hDC,b);const auto pen=CreatePen(PS_SOLID,1,dot);const auto op=SelectObject(d.hDC,pen);const int cy=r.bottom/2;Ellipse(d.hDC,x,cy-ui::px(3,dpi),x+ui::px(6,dpi),cy+ui::px(3,dpi));SelectObject(d.hDC,old);SelectObject(d.hDC,op);DeleteObject(b);DeleteObject(pen);text(d.hDC,p.title.empty()?L"网页加载中":p.title,RECT{x+ui::px(12,dpi),ui::px(7,dpi),r.right-pad,r.bottom-ui::px(p.loaded?7:20,dpi)},ui::text,host->pageFont);if(!p.loaded)text(d.hDC,L"加载中",RECT{x+ui::px(12,dpi),r.bottom-ui::px(20,dpi),r.right-pad,r.bottom-ui::px(3,dpi)},ui::muted,host->smallFont);
 }else{const bool primary=(id==takeoverId||id==returnId||id==confirmId)&&!disabled;const auto target=primary?ui::accent:over?ui::hover:ui::panel;const auto fill=primary||disabled?target:host->feedback(d.hwndItem,target,120);surface(d.hDC,r,fill,fill,ui::px(6,dpi));wchar_t caption[256]{};GetWindowTextW(d.hwndItem,caption,256);const auto color=disabled?ui::disabled:primary?ui::primaryText:id==closePageId?ui::danger:ui::text;
  const wchar_t*glyph=id==backId?L"\uE72B":id==forwardId?L"\uE72A":id==reloadId?L"\uE72C":id==refreshId?L"\uE8B9":id==closePageId?L"\uE74D":nullptr;if(glyph){SelectObject(d.hDC,host->iconFont);SetTextColor(d.hDC,color);SetBkMode(d.hDC,TRANSPARENT);DrawTextW(d.hDC,glyph,-1,&r,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}else{r.left+=pad;r.right-=pad;SetTextColor(d.hDC,color);SetBkMode(d.hDC,TRANSPARENT);SelectObject(d.hDC,host->font);DrawTextW(d.hDC,caption,-1,&r,DT_CENTER|DT_SINGLELINE|DT_VCENTER);}}
 if(focused){RECT cue=d.rcItem;InflateRect(&cue,-ui::px(3,dpi),-ui::px(3,dpi));const auto pen=CreatePen(PS_SOLID,ui::px(2,dpi),ui::accent);const auto op=SelectObject(d.hDC,pen),ob=SelectObject(d.hDC,GetStockObject(NULL_BRUSH));RoundRect(d.hDC,cue.left,cue.top,cue.right,cue.bottom,ui::px(12,dpi),ui::px(12,dpi));SelectObject(d.hDC,op);SelectObject(d.hDC,ob);DeleteObject(pen);}
}
LRESULT CALLBACK coverProc(HWND window,UINT m,WPARAM w,LPARAM l){if(m==WM_PAINT&&host){PAINTSTRUCT ps;auto dc=BeginPaint(window,&ps);RECT r{};GetClientRect(window,&r);const auto brush=CreateSolidBrush(ui::preview);FillRect(dc,&r,brush);DeleteObject(brush);const int pad=ui::px(18,host->dpi);const auto&p=host->pages[host->controls.selected];if(p.thumbnail.empty())text(dc,p.active?L"页面已就绪 · 更新预览查看当前画面":L"等待 Agent 创建网页",RECT{pad,r.bottom/2-ui::px(24,host->dpi),r.right-pad,r.bottom/2+ui::px(24,host->dpi)},ui::muted,host->font);else drawThumbnail(dc,p.thumbnail,RECT{pad,pad,r.right-pad,r.bottom-pad},ui::containerRadius);EndPaint(window,&ps);return 0;}return DefWindowProc(window,m,w,l);}
void paintChrome(HDC dc){RECT r{};GetClientRect(host->window,&r);const auto brush=CreateSolidBrush(ui::bg);FillRect(dc,&r,brush);DeleteObject(brush);const auto&l=host->chrome;const UINT dpi=host->dpi;auto rect=[&](int a,int b,int c,int d){return ui::scale(RECT{a,b,c,d},dpi);};
 const auto pen=CreatePen(PS_SOLID,1,ui::line);const auto old=SelectObject(dc,pen);MoveToEx(dc,0,l.header.bottom,nullptr);LineTo(dc,r.right,l.header.bottom);SelectObject(dc,old);DeleteObject(pen);
 surface(dc,rect(20,8,50,38),ui::panel,ui::panel,ui::px(6,dpi));text(dc,L"\uE737",rect(24,12,47,34),ui::accent,host->iconFont);text(dc,L"Agent 浏览器",rect(60,7,250,27),ui::text,host->font);text(dc,L"任务总览",rect(60,27,250,42),ui::muted,host->smallFont);text(dc,host->status=="ready"?L"已连接 · 专用浏览器":L"环境加载中",RECT{r.right-ui::px(240,dpi),ui::px(9,dpi),r.right-ui::px(22,dpi),ui::px(34,dpi)},ui::muted,host->pageFont);
 text(dc,L"网页工作区",l.sidebarTitle,ui::muted,host->pageFont);for(int n=0;n<2;n++){text(dc,host->pages[n*4].agentLabel,l.agents[n],ui::text,host->pageFont);text(dc,host->pages[n*4].taskLabel+L" · "+host->taskState(n*4),l.tasks[n],ui::muted,host->pageFont);}
 surface(dc,l.viewer,ui::panel,ui::panel,ui::px(8,dpi));surface(dc,l.address,ui::preview,ui::line,ui::px(6,dpi));const auto&p=host->pages[host->controls.selected];const auto&t=host->controls.tasks[demo::owner(host->controls.selected)];const auto&ownerPage=host->pages[demo::owner(host->controls.selected)*4];text(dc,ownerPage.agentLabel+L" / "+ownerPage.taskLabel,l.context,ui::muted,host->pageFont);RECT title=l.title;title.right-=ui::px(130,dpi);text(dc,p.title.empty()?L"任务总览":p.title,title,ui::text,host->largeFont);text(dc,t.human?L"你正在接管 · Agent 已暂停":t.paused?L"Agent 已暂停 · 等待确认":host->controls.viewing?L"只读查看 · 接管后可直接操作":L"最近页面预览 · 点击左侧网页切换观察",l.status,ui::muted,host->pageFont);
 if(host->controls.pending!=demo::Pending::none){surface(dc,l.pending,ui::preview,ui::preview,ui::px(6,dpi));RECT message=l.pending;message.left+=ui::px(12,dpi);text(dc,L"",RECT{message.left,message.top,message.left+ui::px(24,dpi),message.bottom},ui::muted,host->iconFont);message.left+=ui::px(30,dpi);message.right-=ui::px(196,dpi);text(dc,host->controls.pending==demo::Pending::takeover?L"确认接管此任务？Agent 已暂停。":L"确认交还任务？Agent 将恢复。",message,ui::text,host->pageFont);}

}
LRESULT CALLBACK windowProc(HWND window,UINT m,WPARAM w,LPARAM l){if(!host)return DefWindowProc(window,m,w,l);
 if(m==WM_CREATE){host->window=window;outputWindow=window;host->setFonts(GetDpiForWindow(window));BOOL dark=TRUE;DwmSetWindowAttribute(window,20,&dark,sizeof(dark));SetWindowLongPtr(window,GWL_EXSTYLE,GetWindowLongPtr(window,GWL_EXSTYLE)|WS_EX_CONTROLPARENT);
  const std::array<std::pair<int,const wchar_t*>,10> buttons={{{backId,L"后退"},{forwardId,L"前进"},{reloadId,L"刷新"},{overviewId,L"任务总览"},{takeoverId,L"接管此任务"},{returnId,L"交还并返回"},{refreshId,L"更新预览"},{closePageId,L"关闭此页"},{confirmId,L"确认"},{cancelId,L"取消"}}};host->tooltip=CreateWindowExW(WS_EX_TOPMOST,TOOLTIPS_CLASSW,nullptr,WS_POPUP|TTS_ALWAYSTIP|TTS_NOPREFIX,0,0,0,0,window,nullptr,GetModuleHandle(nullptr),nullptr);
  for(const auto&[id,label]:buttons){const auto button=CreateWindowW(L"BUTTON",label,WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_OWNERDRAW,0,0,1,1,window,reinterpret_cast<HMENU>(static_cast<INT_PTR>(id)),nullptr,nullptr);SetWindowSubclass(button,buttonProc,1,0);SendMessage(button,WM_SETFONT,reinterpret_cast<WPARAM>(host->font),TRUE);TOOLINFOW t{sizeof(t)};t.uFlags=TTF_IDISHWND|TTF_SUBCLASS;t.hwnd=window;t.uId=reinterpret_cast<UINT_PTR>(button);t.lpszText=const_cast<wchar_t*>(label);SendMessage(host->tooltip,TTM_ADDTOOLW,0,reinterpret_cast<LPARAM>(&t));}
  for(int i=0;i<8;i++){const auto button=CreateWindowW(L"BUTTON",L"网页",WS_CHILD|WS_TABSTOP|BS_OWNERDRAW,0,0,1,1,window,reinterpret_cast<HMENU>(static_cast<INT_PTR>(pageBaseId+i)),nullptr,nullptr);SetWindowSubclass(button,buttonProc,1,0);SendMessage(button,WM_SETFONT,reinterpret_cast<WPARAM>(host->font),TRUE);TOOLINFOW tip{sizeof(tip)};tip.uFlags=TTF_IDISHWND|TTF_SUBCLASS;tip.hwnd=window;tip.uId=reinterpret_cast<UINT_PTR>(button);tip.lpszText=LPSTR_TEXTCALLBACKW;SendMessage(host->tooltip,TTM_ADDTOOLW,0,reinterpret_cast<LPARAM>(&tip));}
  host->address=CreateWindowExW(0,L"EDIT",L"等待网页",WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_READONLY|ES_AUTOHSCROLL,0,0,1,1,window,reinterpret_cast<HMENU>(static_cast<INT_PTR>(addressId)),nullptr,nullptr);SendMessage(host->address,WM_SETFONT,reinterpret_cast<WPARAM>(host->pageFont),TRUE);SetWindowSubclass(host->address,addressProc,2,0);TOOLINFOW at{sizeof(at)};at.uFlags=TTF_IDISHWND|TTF_SUBCLASS;at.hwnd=window;at.uId=reinterpret_cast<UINT_PTR>(host->address);at.lpszText=LPSTR_TEXTCALLBACKW;SendMessage(host->tooltip,TTM_ADDTOOLW,0,reinterpret_cast<LPARAM>(&at));host->cover=CreateWindowW(L"AgentBrowserNativeCover",L"",WS_CHILD|WS_VISIBLE,0,0,1,1,window,nullptr,GetModuleHandle(nullptr),nullptr);host->updateButtons();return 0;}
 if(m==WM_GETMINMAXINFO){auto*x=reinterpret_cast<MINMAXINFO*>(l);x->ptMinTrackSize={ui::px(ui::minWidth,host->dpi),ui::px(ui::minHeight,host->dpi)};return 0;}
 if(m==WM_DPICHANGED){host->setFonts(HIWORD(w));const auto*r=reinterpret_cast<RECT*>(l);SetWindowPos(window,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE);host->layout();return 0;}
 if(m==WM_NOTIFY&&reinterpret_cast<NMHDR*>(l)->code==TTN_GETDISPINFOW){auto*info=reinterpret_cast<NMTTDISPINFOW*>(l);const HWND control=reinterpret_cast<HWND>(info->hdr.idFrom);const int id=GetDlgCtrlID(control);if(id==addressId)host->tooltipText=host->lastAddress;else if(id>=pageBaseId&&id<pageBaseId+8){const int n=id-pageBaseId;host->tooltipText=host->pages[n].title+L" · "+host->taskState(n);}info->lpszText=host->tooltipText.data();return 0;}
 if(m==WM_CTLCOLORSTATIC&&reinterpret_cast<HWND>(l)==host->address){SetTextColor(reinterpret_cast<HDC>(w),ui::muted);SetBkColor(reinterpret_cast<HDC>(w),ui::preview);static HBRUSH brush=CreateSolidBrush(ui::preview);return reinterpret_cast<LRESULT>(brush);}
 if(m==WM_ACTIVATE&&LOWORD(w)==WA_INACTIVE)host->stopFeedback();if(m==WM_SETTINGCHANGE)host->stopFeedback();if(m==WM_SIZE&&w==SIZE_MINIMIZED)host->stopFeedback();
 if(m==WM_DRAWITEM){paintButton(*reinterpret_cast<DRAWITEMSTRUCT*>(l));return TRUE;}
 if(m==WM_SHOWWINDOW&&w)host->shows++;if(m==WM_SETFOCUS)host->focusEvents++;if(m==WM_SIZE){if(w==SIZE_RESTORED&&host->pending&&host->pending->minimized)host->restoreEvents++;if(w!=SIZE_MINIMIZED)host->layout();return 0;}
 if(m==WM_COMMAND){const HWND child=reinterpret_cast<HWND>(l);DWORD owner=0;if(HIWORD(w)==BN_CLICKED&&child&&child==GetDlgItem(window,LOWORD(w))&&GetParent(child)==window&&GetWindowThreadProcessId(child,&owner)&&owner==GetCurrentProcessId())host->ui(LOWORD(w));return 0;}
 if(m==commandMessage){std::unique_ptr<Command> c(reinterpret_cast<Command*>(l));queuedCommands--;host->command(*c);eventDeadline=0;return 0;}if(m==WM_APP+32){host->error="OUTPUT_WRITE_UNKNOWN";host->controls.failClosed();host->close();return 0;}if(m==WM_TIMER){if(w==captureTimer)host->tickCapture();if(w==closeTimer)host->tickClose();if(w==73)host->tickFeedback();return 0;}
 if(m==WM_LBUTTONDOWN||m==WM_LBUTTONUP||m==WM_MOUSEMOVE||m==WM_MOUSEWHEEL||m==WM_MOUSEHWHEEL||m==WM_RBUTTONDOWN||m==WM_RBUTTONUP){if(host->mouse(m,w,l))return 0;}
 if(m==WM_CAPTURECHANGED){host->resetInputCapture(false);return 0;}if(m==WM_CANCELMODE){host->resetInputCapture();return 0;}if(m==WM_CLOSE){if(!host->closing){host->status="close-requested";for(auto&t:host->controls.tasks)t.paused=true;host->record();}return 0;}if(m==WM_DESTROY){PostQuitMessage(host->error=="NONE"?0:1);return 0;}
 if(m==WM_ERASEBKGND)return 1;if(m==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(window,&ps);paintChrome(dc);EndPaint(window,&ps);return 0;}return DefWindowProc(window,m,w,l);}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,LPWSTR,int){int argc=0;LPWSTR*argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(!argv||argc!=9)return 2;if(std::wstring(argv[1])!=L"--origin"||std::wstring(argv[3])!=L"--data-root"||std::wstring(argv[5])!=L"--output-root"||std::wstring(argv[7])!=L"--proxy-port"){LocalFree(argv);return 2;}HANDLE cActive=OpenMutexW(SYNCHRONIZE,FALSE,L"Local\\AgentBrowser.WP19C.CLI");if(cActive){CloseHandle(cActive);LocalFree(argv);return 23;}HANDLE dActive=OpenMutexW(SYNCHRONIZE,FALSE,L"Local\\AgentBrowser.WP19D.CLI");if(dActive){CloseHandle(dActive);LocalFree(argv);return 23;}struct InstanceLock{HANDLE handle=CreateMutexW(nullptr,FALSE,L"Local\\AgentBrowser.WP19E.CLI");~InstanceLock(){if(handle)CloseHandle(handle);}} instanceLock;const bool already=GetLastError()==ERROR_ALREADY_EXISTS;if(!instanceLock.handle||already){LocalFree(argv);return 23;}const std::wstring origin=argv[2],udf=argv[4],out=argv[6],proxyValue=argv[8];LocalFree(argv);unsigned long proxyPort=0;try{if(proxyValue.empty()||proxyValue.find_first_not_of(L"0123456789")!=std::wstring::npos)return 2;proxyPort=std::stoul(proxyValue);}catch(...){return 2;}if(proxyPort<1024||proxyPort>65535)return 2;const std::wstring prefix=L"http://127.0.0.1:";if(origin.rfind(prefix,0)!=0||origin.find_first_not_of(L"0123456789",prefix.size())!=std::wstring::npos)return 2;unsigned long port=0;try{port=std::stoul(origin.substr(prefix.size()));}catch(...){return 2;}if(port<1024||port>65535||port==19825||GetFileType(GetStdHandle(STD_INPUT_HANDLE))!=FILE_TYPE_PIPE||!startup::preflight())return 3;auto dirs=std::make_shared<owned::Directories>();if(!dirs->create(fs::path(udf),fs::path(out)))return 4;WSADATA winsock{};if(WSAStartup(MAKEWORD(2,2),&winsock))return 7;SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);if(FAILED(CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)))return 5;host=std::make_shared<Host>();host->proxyPort=static_cast<unsigned>(proxyPort);host->origin=origin;host->policy.fixture=origin;host->udf=udf;host->directories=dirs;for(int i=0;i<8;i++)host->pages[i].scopeGeneration=0,host->pages[i].url=origin+(i<4?L"/agent-a":L"/agent-b");WNDCLASSW c{};c.hInstance=instance;c.hCursor=LoadCursor(nullptr,IDC_ARROW);c.lpfnWndProc=coverProc;c.lpszClassName=L"AgentBrowserNativeCover";RegisterClassW(&c);c.lpfnWndProc=windowProc;c.lpszClassName=L"AgentBrowserNativeSingleWindow";RegisterClassW(&c);HWND window=CreateWindowW(c.lpszClassName,L"Agent 浏览器 · 任务总览",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,ui::px(1200,GetDpiForSystem()),ui::px(850,GetDpiForSystem()),nullptr,nullptr,instance,nullptr);if(!window){host.reset();CoUninitialize();return 6;}ShowWindow(window,SW_SHOW);host->initialize();
 std::thread([window]{std::string line;bool discard=false;char buffer[1024];DWORD n=0;while(ReadFile(GetStdHandle(STD_INPUT_HANDLE),buffer,sizeof(buffer),&n,nullptr)&&n){for(DWORD i=0;i<n;i++){if(buffer[i]=='\n'){auto c=discard?std::unique_ptr<Command>{}:parseCommand(line);line.clear();discard=false;if(c){if(queuedCommands.fetch_add(1)>=32){queuedCommands--;emit("{\"kind\":\"protocol-error\",\"code\":\"QUEUE_LIMIT\"}");continue;}if(!PostMessage(window,commandMessage,0,reinterpret_cast<LPARAM>(c.get()))){queuedCommands--;continue;}c.release();}}else if(buffer[i]!='\r'){if(!discard&&line.size()<131072)line+=buffer[i];else {line.clear();discard=true;}}}}auto close=std::make_unique<Command>();close->deadline=GetTickCount64()+8000;close->id=1;close->operation="close";queuedCommands++;if(PostMessage(window,commandMessage,0,reinterpret_cast<LPARAM>(close.get())))close.release();else queuedCommands--;}).detach();MSG msg{};while(GetMessage(&msg,nullptr,0,0)>0){const HWND focus=GetFocus();wchar_t cls[32]{};GetClassNameW(focus,cls,32);if(focus==host->address&&((msg.message==WM_KEYDOWN&&msg.wParam==VK_RETURN)||(msg.message==WM_CHAR&&msg.wParam==VK_RETURN)))continue;if((focus==window||wcscmp(cls,L"Button")==0||wcscmp(cls,L"Edit")==0)&&IsDialogMessageW(window,&msg))continue;TranslateMessage(&msg);DispatchMessage(&msg);}host->close();host.reset();CoUninitialize();return static_cast<int>(msg.wParam);}
